# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/bindings/rust"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/bindings/rust/fuzz"
    schedule:
      interval: "weekly"
  - package-ecosystem: "hex"
    directory: "/bindings/elixir"
    schedule:
      interval: "weekly"
