// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 Hyperpolymath

//! Zig FFI Bridge for Proven
//!
//! This build file compiles the Idris 2 RefC output and wraps it in a
//! stable C ABI that can be consumed by Python, Rust, Go, and other languages.
//!
//! Uses idris2-zig-ffi for generic Idris 2 FFI infrastructure.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Get idris2-zig-ffi dependency
    const idris2_zig_ffi_dep = b.dependency("idris2_zig_ffi", .{
        .target = target,
        .optimize = optimize,
    });
    const idris2_zig_ffi_mod = idris2_zig_ffi_dep.module("idris2_zig_ffi");

    // Static library for embedding
    const lib = b.addStaticLibrary(.{
        .name = "proven",
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });

    // Add idris2-zig-ffi module
    lib.root_module.addImport("idris2_zig_ffi", idris2_zig_ffi_mod);

    // Include the Idris 2 RefC runtime headers
    lib.addIncludePath(b.path("include"));

    // Link the Idris 2 RefC output (generated by `idris2 --codegen refc`)
    // This path will be set after running `idris2 --codegen refc -o proven src/Proven.idr`
    if (b.option([]const u8, "idris-refc", "Path to Idris 2 RefC output directory")) |refc_path| {
        lib.addIncludePath(.{ .cwd_relative = refc_path });
        lib.addCSourceFiles(.{
            .root = .{ .cwd_relative = refc_path },
            .files = &.{
                "proven.c",
            },
            .flags = &.{"-std=c11"},
        });
    }

    // System dependencies
    lib.linkLibC();

    b.installArtifact(lib);

    // Shared library for dynamic loading (Python ctypes, etc.)
    const shared_lib = b.addSharedLibrary(.{
        .name = "proven",
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });

    // Add idris2-zig-ffi module to shared lib
    shared_lib.root_module.addImport("idris2_zig_ffi", idris2_zig_ffi_mod);

    shared_lib.addIncludePath(b.path("include"));
    shared_lib.linkLibC();

    b.installArtifact(shared_lib);

    // ========================================================================
    // WASM targets (using idris2-zig-ffi infrastructure)
    // ========================================================================

    // Browser WASM
    const wasm_browser = b.addSharedLibrary(.{
        .name = "proven",
        .root_source_file = b.path("src/main.zig"),
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
        }),
        .optimize = .ReleaseSmall,
    });
    wasm_browser.root_module.addImport("idris2_zig_ffi", idris2_zig_ffi_dep.module("idris2_zig_ffi"));
    wasm_browser.rdynamic = true;

    const wasm_browser_step = b.step("wasm", "Build WASM library for browsers");
    const wasm_browser_install = b.addInstallArtifact(wasm_browser, .{});
    wasm_browser_step.dependOn(&wasm_browser_install.step);

    // WASI
    const wasm_wasi = b.addSharedLibrary(.{
        .name = "proven",
        .root_source_file = b.path("src/main.zig"),
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .wasi,
        }),
        .optimize = .ReleaseSmall,
    });
    wasm_wasi.root_module.addImport("idris2_zig_ffi", idris2_zig_ffi_dep.module("idris2_zig_ffi"));
    wasm_wasi.rdynamic = true;

    const wasm_wasi_step = b.step("wasi", "Build WASI library for runtimes");
    const wasm_wasi_install = b.addInstallArtifact(wasm_wasi, .{});
    wasm_wasi_step.dependOn(&wasm_wasi_install.step);

    // All WASM targets
    const all_wasm_step = b.step("all-wasm", "Build all WASM targets");
    all_wasm_step.dependOn(wasm_browser_step);
    all_wasm_step.dependOn(wasm_wasi_step);

    // Header file installation (optional - for C/C++ consumers only)
    // The Zig library exposes a C ABI, but consumers using Zig, Rust (via zig-cc),
    // or other modern FFI mechanisms don't need a header file.
    // Uncomment if you need C header for legacy interop:
    // b.installFile("include/proven.h", "include/proven.h");

    // Tests
    const main_tests = b.addTest(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    main_tests.root_module.addImport("idris2_zig_ffi", idris2_zig_ffi_mod);

    const run_main_tests = b.addRunArtifact(main_tests);
    const test_step = b.step("test", "Run library tests");
    test_step.dependOn(&run_main_tests.step);
}
