// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Proven_Bitwise from "./Proven_Bitwise.res.js";

function policyResultAnd(a, b) {
  switch (a) {
    case "Allow" :
        switch (b) {
          case "Allow" :
              return "Allow";
          case "Deny" :
          case "NotApplicable" :
              break;
          
        }
        break;
    case "Deny" :
        return "Deny";
    case "NotApplicable" :
        break;
    
  }
  switch (b) {
    case "Deny" :
        return "Deny";
    case "Allow" :
    case "NotApplicable" :
        return "NotApplicable";
    
  }
}

function policyResultOr(a, b) {
  switch (a) {
    case "Allow" :
        return "Allow";
    case "Deny" :
        switch (b) {
          case "Allow" :
              break;
          case "Deny" :
              return "Deny";
          case "NotApplicable" :
              return "NotApplicable";
          
        }
        break;
    case "NotApplicable" :
        break;
    
  }
  switch (b) {
    case "Allow" :
        return "Allow";
    case "Deny" :
    case "NotApplicable" :
        return "NotApplicable";
    
  }
}

function policyResultNot(r) {
  switch (r) {
    case "Allow" :
        return "Deny";
    case "Deny" :
        return "Allow";
    case "NotApplicable" :
        return "NotApplicable";
    
  }
}

function policyResultToBool(r) {
  return r === "Allow";
}

function compareValues(a, b, op) {
  switch (a.TAG) {
    case "Boolean" :
        if (b.TAG !== "Boolean") {
          return ;
        }
        var vb = b._0;
        var va = a._0;
        switch (op) {
          case "Equal" :
              return va === vb;
          case "NotEqual" :
              return va !== vb;
          default:
            return ;
        }
    case "Integer" :
        if (b.TAG !== "Integer") {
          return ;
        }
        var vb$1 = b._0;
        var va$1 = a._0;
        switch (op) {
          case "Equal" :
              return va$1 === vb$1;
          case "NotEqual" :
              return va$1 !== vb$1;
          case "LessThan" :
              return va$1 < vb$1;
          case "LessEqual" :
              return va$1 <= vb$1;
          case "GreaterThan" :
              return va$1 > vb$1;
          case "GreaterEqual" :
              return va$1 >= vb$1;
          default:
            return ;
        }
    case "Float" :
        if (b.TAG !== "Float") {
          return ;
        }
        var vb$2 = b._0;
        var va$2 = a._0;
        switch (op) {
          case "Equal" :
              return va$2 === vb$2;
          case "NotEqual" :
              return va$2 !== vb$2;
          case "LessThan" :
              return va$2 < vb$2;
          case "LessEqual" :
              return va$2 <= vb$2;
          case "GreaterThan" :
              return va$2 > vb$2;
          case "GreaterEqual" :
              return va$2 >= vb$2;
          default:
            return ;
        }
    case "String" :
        var va$3 = a._0;
        switch (b.TAG) {
          case "String" :
              var vb$3 = b._0;
              switch (op) {
                case "Equal" :
                    return va$3 === vb$3;
                case "NotEqual" :
                    return va$3 !== vb$3;
                case "Contains" :
                    return va$3.includes(vb$3);
                case "StartsWith" :
                    return va$3.startsWith(vb$3);
                case "EndsWith" :
                    return va$3.endsWith(vb$3);
                default:
                  return ;
              }
          case "StringList" :
              if (op === "MatchesAny") {
                return b._0.includes(va$3);
              } else {
                return ;
              }
          default:
            return ;
        }
    case "StringList" :
        return ;
    
  }
}

function createAttributeMap() {
  return {};
}

function setAttribute(attrs, key, value) {
  attrs[key] = value;
}

var getAttribute = Js_dict.get;

function hasAttribute(attrs, key) {
  return Belt_Option.isSome(Js_dict.get(attrs, key));
}

function evaluateRule(rule, attrs) {
  var allConditionsMet = rule.conditions.every(function (condition) {
        var attrValue = Js_dict.get(attrs, condition.attribute);
        if (attrValue === undefined) {
          return false;
        }
        var result = compareValues(attrValue, condition.value, condition.operator);
        if (result !== undefined) {
          return result;
        } else {
          return false;
        }
      });
  if (allConditionsMet) {
    return rule.effect;
  } else {
    return "NotApplicable";
  }
}

function createPolicySet(algorithmOpt) {
  var algorithm = algorithmOpt !== undefined ? algorithmOpt : "DenyOverrides";
  return {
          rules: [],
          algorithm: algorithm,
          defaultResult: "Deny"
        };
}

function addRule(policySet, rule) {
  return {
          rules: policySet.rules.concat([rule]),
          algorithm: policySet.algorithm,
          defaultResult: policySet.defaultResult
        };
}

function evaluatePolicySet(policySet, attrs) {
  if (policySet.rules.length === 0) {
    return policySet.defaultResult;
  }
  var results = policySet.rules.map(function (rule) {
        return evaluateRule(rule, attrs);
      });
  var allowCount = results.filter(function (r) {
        return r === "Allow";
      }).length;
  var denyCount = results.filter(function (r) {
        return r === "Deny";
      }).length;
  var applicableCount = results.filter(function (r) {
        return r !== "NotApplicable";
      }).length;
  if (applicableCount === 0) {
    return policySet.defaultResult;
  }
  var match = policySet.algorithm;
  switch (match) {
    case "FirstApplicable" :
        var r = results.find(function (r) {
              return r !== "NotApplicable";
            });
        if (r !== undefined) {
          return r;
        } else {
          return policySet.defaultResult;
        }
    case "DenyOverrides" :
        if (denyCount > 0) {
          return "Deny";
        } else {
          return "Allow";
        }
    case "AllowOverrides" :
        if (allowCount > 0) {
          return "Allow";
        } else {
          return "Deny";
        }
    case "UnanimousAllow" :
        if (allowCount === applicableCount) {
          return "Allow";
        } else {
          return "Deny";
        }
    case "UnanimousDeny" :
        if (denyCount === applicableCount) {
          return "Deny";
        } else {
          return "Allow";
        }
    
  }
}

function isAllowed(policySet, attrs) {
  return evaluatePolicySet(policySet, attrs) === "Allow";
}

function isFeatureEnabledFor(flag, userId) {
  if (!flag.enabled) {
    return false;
  }
  if (flag.rolloutPercentage >= 100) {
    return true;
  }
  if (flag.rolloutPercentage === 0) {
    return false;
  }
  var hash = userId % 100;
  return hash < flag.rolloutPercentage;
}

var weekdays = Proven_Bitwise.lor(Proven_Bitwise.lor(Proven_Bitwise.lor(Proven_Bitwise.lor(2, 4), 8), 16), 32);

var weekend = Proven_Bitwise.lor(64, 1);

var allDays = Proven_Bitwise.lor(weekdays, weekend);

function isTimeActiveAt(policy, hour, dayOfWeek) {
  if (hour < 0 || hour > 23) {
    return false;
  }
  if (dayOfWeek < 0 || dayOfWeek > 6) {
    return false;
  }
  var dayMask = Proven_Bitwise.lsl(1, dayOfWeek);
  if (Proven_Bitwise.land(policy.days, dayMask) === 0) {
    return false;
  } else if (policy.startHour <= policy.endHour) {
    if (hour >= policy.startHour) {
      return hour < policy.endHour;
    } else {
      return false;
    }
  } else if (hour >= policy.startHour) {
    return true;
  } else {
    return hour < policy.endHour;
  }
}

var businessHoursPolicy = {
  startHour: 9,
  endHour: 17,
  days: weekdays
};

var alwaysActivePolicy = {
  startHour: 0,
  endHour: 24,
  days: allDays
};

function allow(conditions) {
  return {
          effect: "Allow",
          conditions: conditions,
          description: undefined
        };
}

function deny(conditions) {
  return {
          effect: "Deny",
          conditions: conditions,
          description: undefined
        };
}

function allowWithDescription(conditions, desc) {
  return {
          effect: "Allow",
          conditions: conditions,
          description: desc
        };
}

function denyWithDescription(conditions, desc) {
  return {
          effect: "Deny",
          conditions: conditions,
          description: desc
        };
}

var RuleBuilder = {
  allow: allow,
  deny: deny,
  allowWithDescription: allowWithDescription,
  denyWithDescription: denyWithDescription
};

function stringEquals(attr, val) {
  return {
          attribute: attr,
          operator: "Equal",
          value: {
            TAG: "String",
            _0: val
          }
        };
}

function stringNotEquals(attr, val) {
  return {
          attribute: attr,
          operator: "NotEqual",
          value: {
            TAG: "String",
            _0: val
          }
        };
}

function intEquals(attr, val) {
  return {
          attribute: attr,
          operator: "Equal",
          value: {
            TAG: "Integer",
            _0: val
          }
        };
}

function intGreaterThan(attr, val) {
  return {
          attribute: attr,
          operator: "GreaterThan",
          value: {
            TAG: "Integer",
            _0: val
          }
        };
}

function intLessThan(attr, val) {
  return {
          attribute: attr,
          operator: "LessThan",
          value: {
            TAG: "Integer",
            _0: val
          }
        };
}

function boolEquals(attr, val) {
  return {
          attribute: attr,
          operator: "Equal",
          value: {
            TAG: "Boolean",
            _0: val
          }
        };
}

function stringContains(attr, val) {
  return {
          attribute: attr,
          operator: "Contains",
          value: {
            TAG: "String",
            _0: val
          }
        };
}

function stringStartsWith(attr, val) {
  return {
          attribute: attr,
          operator: "StartsWith",
          value: {
            TAG: "String",
            _0: val
          }
        };
}

function stringEndsWith(attr, val) {
  return {
          attribute: attr,
          operator: "EndsWith",
          value: {
            TAG: "String",
            _0: val
          }
        };
}

function matchesAny(attr, values) {
  return {
          attribute: attr,
          operator: "MatchesAny",
          value: {
            TAG: "StringList",
            _0: values
          }
        };
}

var ConditionBuilder = {
  stringEquals: stringEquals,
  stringNotEquals: stringNotEquals,
  intEquals: intEquals,
  intGreaterThan: intGreaterThan,
  intLessThan: intLessThan,
  boolEquals: boolEquals,
  stringContains: stringContains,
  stringStartsWith: stringStartsWith,
  stringEndsWith: stringEndsWith,
  matchesAny: matchesAny
};

var requireAuthenticated_conditions = [{
    attribute: "authenticated",
    operator: "Equal",
    value: {
      TAG: "Boolean",
      _0: false
    }
  }];

var requireAuthenticated = {
  effect: "Deny",
  conditions: requireAuthenticated_conditions,
  description: undefined
};

var allowAdmin_conditions = [{
    attribute: "role",
    operator: "Equal",
    value: {
      TAG: "String",
      _0: "admin"
    }
  }];

var allowAdmin = {
  effect: "Allow",
  conditions: allowAdmin_conditions,
  description: undefined
};

var denyBanned_conditions = [{
    attribute: "banned",
    operator: "Equal",
    value: {
      TAG: "Boolean",
      _0: true
    }
  }];

var denyBanned = {
  effect: "Deny",
  conditions: denyBanned_conditions,
  description: undefined
};

function rateLimitExceeded(limit) {
  return {
          effect: "Deny",
          conditions: [intGreaterThan("request_count", limit)],
          description: undefined
        };
}

var CommonPolicies = {
  requireAuthenticated: requireAuthenticated,
  allowAdmin: allowAdmin,
  denyBanned: denyBanned,
  rateLimitExceeded: rateLimitExceeded
};

var sunday = 1;

var monday = 2;

var tuesday = 4;

var wednesday = 8;

var thursday = 16;

var friday = 32;

var saturday = 64;

export {
  policyResultAnd ,
  policyResultOr ,
  policyResultNot ,
  policyResultToBool ,
  compareValues ,
  createAttributeMap ,
  setAttribute ,
  getAttribute ,
  hasAttribute ,
  evaluateRule ,
  createPolicySet ,
  addRule ,
  evaluatePolicySet ,
  isAllowed ,
  isFeatureEnabledFor ,
  sunday ,
  monday ,
  tuesday ,
  wednesday ,
  thursday ,
  friday ,
  saturday ,
  weekdays ,
  weekend ,
  allDays ,
  isTimeActiveAt ,
  businessHoursPolicy ,
  alwaysActivePolicy ,
  RuleBuilder ,
  ConditionBuilder ,
  CommonPolicies ,
}
/* weekdays Not a pure module */
