// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function hasInjection(s) {
  if (s.includes(";") || s.includes("\r")) {
    return true;
  } else {
    return s.includes("\n");
  }
}

function getPrefix(name) {
  if (name.startsWith("__Host-")) {
    return "HostPrefix";
  } else if (name.startsWith("__Secure-")) {
    return "SecurePrefix";
  } else {
    return "NoPrefix";
  }
}

var defaultAttributes = {
  domain: undefined,
  path: "/",
  maxAge: undefined,
  secure: true,
  httpOnly: true,
  sameSite: "Lax",
  partitioned: false
};

var sessionAttributes = {
  domain: undefined,
  path: "/",
  maxAge: undefined,
  secure: true,
  httpOnly: true,
  sameSite: "Strict",
  partitioned: false
};

function validateName(name) {
  if (name.length === 0 || name.length > 256 || hasInjection(name)) {
    return ;
  } else {
    return name;
  }
}

function validateValue(value) {
  if (value.length > 4096 || hasInjection(value)) {
    return ;
  } else {
    return value;
  }
}

function validatePrefix(name, attrs) {
  var match = getPrefix(name);
  switch (match) {
    case "NoPrefix" :
        return true;
    case "SecurePrefix" :
        return attrs.secure;
    case "HostPrefix" :
        if (attrs.secure && Belt_Option.isNone(attrs.domain)) {
          return Caml_obj.equal(attrs.path, "/");
        } else {
          return false;
        }
    
  }
}

function validateSameSite(attrs) {
  var match = attrs.sameSite;
  if (match === undefined) {
    return true;
  }
  switch (match) {
    case "Strict" :
    case "Lax" :
        return true;
    case "SameSiteNone" :
        return attrs.secure;
    
  }
}

function make(name, value, attrs) {
  var match = validateName(name);
  var match$1 = validateValue(value);
  if (match !== undefined && match$1 !== undefined && !(!validatePrefix(match, attrs) || !validateSameSite(attrs))) {
    return {
            name: match,
            value: match$1,
            attributes: attrs
          };
  }
  
}

function makeDefault(name, value) {
  return make(name, value, defaultAttributes);
}

function makeSession(name, value) {
  return make(name, value, sessionAttributes);
}

function sameSiteToString(ss) {
  switch (ss) {
    case "Strict" :
        return "Strict";
    case "Lax" :
        return "Lax";
    case "SameSiteNone" :
        return "None";
    
  }
}

function buildSetCookie(c) {
  var base = c.name + "=" + c.value;
  var parts = [base];
  var d = c.attributes.domain;
  var parts$1 = d !== undefined ? parts.concat(["Domain=" + d]) : parts;
  var p = c.attributes.path;
  var parts$2 = p !== undefined ? parts$1.concat(["Path=" + p]) : parts$1;
  var age = c.attributes.maxAge;
  var parts$3 = age !== undefined ? parts$2.concat(["Max-Age=" + String(age)]) : parts$2;
  var parts$4 = c.attributes.secure ? parts$3.concat(["Secure"]) : parts$3;
  var parts$5 = c.attributes.httpOnly ? parts$4.concat(["HttpOnly"]) : parts$4;
  var ss = c.attributes.sameSite;
  var parts$6 = ss !== undefined ? parts$5.concat(["SameSite=" + sameSiteToString(ss)]) : parts$5;
  var parts$7 = c.attributes.partitioned ? parts$6.concat(["Partitioned"]) : parts$6;
  return parts$7.join("; ");
}

function buildDeleteCookie(name) {
  return name + "=; Max-Age=0; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT";
}

function parseCookieHeader(header) {
  return header.split(";").filter(function (s) {
                return s.trim().length > 0;
              }).map(function (pair) {
              var trimmed = pair.trim();
              var idx = trimmed.indexOf("=");
              if (idx !== -1) {
                return [
                        trimmed.slice(0, idx).trim(),
                        trimmed.slice(idx + 1 | 0).trim()
                      ];
              } else {
                return [
                        trimmed,
                        ""
                      ];
              }
            });
}

var strictAttributes = {
  domain: undefined,
  path: "/",
  maxAge: undefined,
  secure: true,
  httpOnly: true,
  sameSite: "Strict",
  partitioned: false
};

var oneHour = 3600;

var oneDay = 86400;

var oneWeek = 604800;

var thirtyDays = 2592000;

var oneYear = 31536000;

export {
  hasInjection ,
  getPrefix ,
  defaultAttributes ,
  sessionAttributes ,
  strictAttributes ,
  validateName ,
  validateValue ,
  validatePrefix ,
  validateSameSite ,
  make ,
  makeDefault ,
  makeSession ,
  sameSiteToString ,
  buildSetCookie ,
  buildDeleteCookie ,
  parseCookieHeader ,
  oneHour ,
  oneDay ,
  oneWeek ,
  thirtyDays ,
  oneYear ,
}
/* No side effect */
