// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Safe_mlJs from "../../javascript/src/safe_ml.js";

function sigmoid(prim) {
  return Safe_mlJs.SafeML.sigmoid(prim);
}

function relu(prim) {
  return Safe_mlJs.SafeML.relu(prim);
}

function leakyRelu(prim0, prim1) {
  return Safe_mlJs.SafeML.leakyRelu(prim0, prim1);
}

function clamp(prim0, prim1, prim2) {
  return Safe_mlJs.SafeML.clamp(prim0, prim1, prim2);
}

var SafeMlJs = {
  sigmoid: sigmoid,
  relu: relu,
  leakyRelu: leakyRelu,
  clamp: clamp
};

export {
  SafeMlJs ,
  sigmoid ,
  relu ,
  leakyRelu ,
  clamp ,
}
/* ../../javascript/src/safe_ml.js Not a pure module */
