// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Proven_Bitwise from "./Proven_Bitwise.res.js";

var noPermission = {
  read: false,
  write: false,
  execute: false,
  delete: false,
  admin: false,
  delegate: false,
  revoke: false
};

var readOnlyPermission = {
  read: true,
  write: false,
  execute: false,
  delete: false,
  admin: false,
  delegate: false,
  revoke: false
};

var readWritePermission = {
  read: true,
  write: true,
  execute: false,
  delete: false,
  admin: false,
  delegate: false,
  revoke: false
};

function permissionIncludes(self, other) {
  if ((!other.read || self.read) && (!other.write || self.write) && (!other.execute || self.execute) && (!other.delete || self.delete) && (!other.admin || self.admin) && (!other.delegate || self.delegate)) {
    if (other.revoke) {
      return self.revoke;
    } else {
      return true;
    }
  } else {
    return false;
  }
}

function permissionCombine(a, b) {
  return {
          read: a.read || b.read,
          write: a.write || b.write,
          execute: a.execute || b.execute,
          delete: a.delete || b.delete,
          admin: a.admin || b.admin,
          delegate: a.delegate || b.delegate,
          revoke: a.revoke || b.revoke
        };
}

function permissionIntersect(a, b) {
  return {
          read: a.read && b.read,
          write: a.write && b.write,
          execute: a.execute && b.execute,
          delete: a.delete && b.delete,
          admin: a.admin && b.admin,
          delegate: a.delegate && b.delegate,
          revoke: a.revoke && b.revoke
        };
}

function permissionToByte(p) {
  var result = 0;
  if (p.read) {
    result = Proven_Bitwise.lor(result, 1);
  }
  if (p.write) {
    result = Proven_Bitwise.lor(result, 2);
  }
  if (p.execute) {
    result = Proven_Bitwise.lor(result, 4);
  }
  if (p.delete) {
    result = Proven_Bitwise.lor(result, 8);
  }
  if (p.admin) {
    result = Proven_Bitwise.lor(result, 16);
  }
  if (p.delegate) {
    result = Proven_Bitwise.lor(result, 32);
  }
  if (p.revoke) {
    result = Proven_Bitwise.lor(result, 64);
  }
  return result;
}

function permissionFromByte($$byte) {
  return {
          read: Proven_Bitwise.land($$byte, 1) !== 0,
          write: Proven_Bitwise.land($$byte, 2) !== 0,
          execute: Proven_Bitwise.land($$byte, 4) !== 0,
          delete: Proven_Bitwise.land($$byte, 8) !== 0,
          admin: Proven_Bitwise.land($$byte, 16) !== 0,
          delegate: Proven_Bitwise.land($$byte, 32) !== 0,
          revoke: Proven_Bitwise.land($$byte, 64) !== 0
        };
}

function hasAnyPermission(p) {
  if (p.read || p.write || p.execute || p.delete || p.admin || p.delegate) {
    return true;
  } else {
    return p.revoke;
  }
}

function hasNoPermission(p) {
  return !hasAnyPermission(p);
}

function makeResourceId(namespace, identifier) {
  var ns = namespace.slice(0, 16);
  var id = identifier.slice(0, 32);
  return {
          namespace: ns,
          identifier: id
        };
}

function makeWildcardResource(namespace) {
  return makeResourceId(namespace, "*");
}

function resourceMatches(pattern, target) {
  if (pattern.namespace !== target.namespace) {
    return false;
  } else if (pattern.identifier === "*") {
    return true;
  } else {
    return pattern.identifier === target.identifier;
  }
}

function resourceEquals(a, b) {
  if (a.namespace === b.namespace) {
    return a.identifier === b.identifier;
  } else {
    return false;
  }
}

function isExpired(cap) {
  if (cap.expiresAt === 0.0) {
    return false;
  } else {
    return Date.now() > cap.expiresAt * 1000.0;
  }
}

function isValid(cap) {
  if (cap.revoked) {
    return false;
  } else {
    return !isExpired(cap);
  }
}

function hasPermission(cap, perm) {
  return permissionIncludes(cap.permissions, perm);
}

function canDelegate(cap) {
  if (cap.permissions.delegate) {
    return cap.delegationDepth < cap.maxDelegationDepth;
  } else {
    return false;
  }
}

function remainingTime(cap) {
  if (cap.expiresAt === 0.0) {
    return 0.0;
  }
  var now = Date.now() / 1000.0;
  var remaining = cap.expiresAt - now;
  if (remaining > 0.0) {
    return remaining;
  } else {
    return 0.0;
  }
}

function generateRandomId() {
  var result = "";
  for(var _for = 0; _for <= 31; ++_for){
    var idx = Js_math.floor_int(Math.random() * 16.0);
    result = result + "0123456789abcdef".charAt(idx);
  }
  return result;
}

function generateSignature() {
  var result = "";
  for(var _for = 0; _for <= 63; ++_for){
    var idx = Js_math.floor_int(Math.random() * 16.0);
    result = result + "0123456789abcdef".charAt(idx);
  }
  return result;
}

function createCapability(resource, permissions, expirySecondsOpt, maxDelegationOpt) {
  var expirySeconds = expirySecondsOpt !== undefined ? expirySecondsOpt : 3600.0;
  var maxDelegation = maxDelegationOpt !== undefined ? maxDelegationOpt : 3;
  var now = Date.now() / 1000.0;
  return {
          id: generateRandomId(),
          resource: resource,
          permissions: permissions,
          createdAt: now,
          expiresAt: expirySeconds > 0.0 ? now + expirySeconds : 0.0,
          delegationDepth: 0,
          maxDelegationDepth: maxDelegation,
          revoked: false,
          signature: generateSignature()
        };
}

function delegateCapability(parent, newPermissions) {
  if (!isValid(parent)) {
    return {
            TAG: "Error",
            _0: "ExpiredCapability"
          };
  }
  if (!canDelegate(parent)) {
    return {
            TAG: "Error",
            _0: "DelegationNotAllowed"
          };
  }
  if (!permissionIncludes(parent.permissions, newPermissions)) {
    return {
            TAG: "Error",
            _0: "InsufficientPermissions"
          };
  }
  var now = Date.now() / 1000.0;
  return {
          TAG: "Ok",
          _0: {
            id: generateRandomId(),
            resource: parent.resource,
            permissions: permissionIntersect(parent.permissions, newPermissions),
            createdAt: now,
            expiresAt: parent.expiresAt,
            delegationDepth: parent.delegationDepth + 1 | 0,
            maxDelegationDepth: parent.maxDelegationDepth,
            revoked: false,
            signature: generateSignature()
          }
        };
}

function validateCapability(cap, resource, requiredPermission) {
  if (cap.revoked) {
    return {
            TAG: "Error",
            _0: "CapabilityRevoked"
          };
  } else if (isExpired(cap)) {
    return {
            TAG: "Error",
            _0: "ExpiredCapability"
          };
  } else if (resourceMatches(cap.resource, resource)) {
    if (hasPermission(cap, requiredPermission)) {
      return {
              TAG: "Ok",
              _0: undefined
            };
    } else {
      return {
              TAG: "Error",
              _0: "InsufficientPermissions"
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: "InvalidResource"
          };
  }
}

function checkAccess(cap, resource, requiredPermission) {
  var match = validateCapability(cap, resource, requiredPermission);
  if (match.TAG === "Ok") {
    return true;
  } else {
    return false;
  }
}

function formatCapabilityId(cap) {
  return cap.id.slice(0, 8) + "...";
}

function serializeCapability(cap) {
  var json = {};
  json["id"] = cap.id;
  json["namespace"] = cap.resource.namespace;
  json["identifier"] = cap.resource.identifier;
  json["permissions"] = permissionToByte(cap.permissions);
  json["createdAt"] = cap.createdAt;
  json["expiresAt"] = cap.expiresAt;
  json["delegationDepth"] = cap.delegationDepth;
  json["maxDelegationDepth"] = cap.maxDelegationDepth;
  json["revoked"] = cap.revoked;
  json["signature"] = cap.signature;
  return JSON.stringify(json);
}

function deserializeCapability(jsonString) {
  try {
    var json = JSON.parse(jsonString);
    var obj = Js_json.classify(json);
    if (typeof obj !== "object") {
      return {
              TAG: "Error",
              _0: "MalformedToken"
            };
    }
    if (obj.TAG !== "JSONObject") {
      return {
              TAG: "Error",
              _0: "MalformedToken"
            };
    }
    var obj$1 = obj._0;
    var getString = function (key) {
      var v = Js_dict.get(obj$1, key);
      if (v === undefined) {
        return ;
      }
      var s = Js_json.classify(v);
      if (typeof s !== "object" || s.TAG !== "JSONString") {
        return ;
      } else {
        return s._0;
      }
    };
    var getNumber = function (key) {
      var v = Js_dict.get(obj$1, key);
      if (v === undefined) {
        return ;
      }
      var n = Js_json.classify(v);
      if (typeof n !== "object" || n.TAG !== "JSONNumber") {
        return ;
      } else {
        return n._0;
      }
    };
    var getBool = function (key) {
      var v = Js_dict.get(obj$1, key);
      if (v === undefined) {
        return ;
      }
      var match = Js_json.classify(v);
      if (typeof match === "object") {
        return ;
      }
      switch (match) {
        case "JSONFalse" :
            return false;
        case "JSONTrue" :
            return true;
        default:
          return ;
      }
    };
    var match = getString("id");
    var match$1 = getString("namespace");
    var match$2 = getString("identifier");
    var match$3 = getNumber("permissions");
    var match$4 = getNumber("createdAt");
    var match$5 = getNumber("expiresAt");
    var match$6 = getNumber("delegationDepth");
    var match$7 = getNumber("maxDelegationDepth");
    var match$8 = getBool("revoked");
    var match$9 = getString("signature");
    if (match !== undefined && match$1 !== undefined && match$2 !== undefined && match$3 !== undefined && match$4 !== undefined && match$5 !== undefined && match$6 !== undefined && match$7 !== undefined && match$8 !== undefined && match$9 !== undefined) {
      return {
              TAG: "Ok",
              _0: {
                id: match,
                resource: {
                  namespace: match$1,
                  identifier: match$2
                },
                permissions: permissionFromByte(match$3 | 0),
                createdAt: match$4,
                expiresAt: match$5,
                delegationDepth: match$6 | 0,
                maxDelegationDepth: match$7 | 0,
                revoked: match$8,
                signature: match$9
              }
            };
    } else {
      return {
              TAG: "Error",
              _0: "MalformedToken"
            };
    }
  }
  catch (exn){
    return {
            TAG: "Error",
            _0: "MalformedToken"
          };
  }
}

function withRead(p) {
  return {
          read: true,
          write: p.write,
          execute: p.execute,
          delete: p.delete,
          admin: p.admin,
          delegate: p.delegate,
          revoke: p.revoke
        };
}

function withWrite(p) {
  return {
          read: p.read,
          write: true,
          execute: p.execute,
          delete: p.delete,
          admin: p.admin,
          delegate: p.delegate,
          revoke: p.revoke
        };
}

function withExecute(p) {
  return {
          read: p.read,
          write: p.write,
          execute: true,
          delete: p.delete,
          admin: p.admin,
          delegate: p.delegate,
          revoke: p.revoke
        };
}

function withDelete(p) {
  return {
          read: p.read,
          write: p.write,
          execute: p.execute,
          delete: true,
          admin: p.admin,
          delegate: p.delegate,
          revoke: p.revoke
        };
}

function withAdmin(p) {
  return {
          read: p.read,
          write: p.write,
          execute: p.execute,
          delete: p.delete,
          admin: true,
          delegate: p.delegate,
          revoke: p.revoke
        };
}

function withDelegate(p) {
  return {
          read: p.read,
          write: p.write,
          execute: p.execute,
          delete: p.delete,
          admin: p.admin,
          delegate: true,
          revoke: p.revoke
        };
}

function withRevoke(p) {
  return {
          read: p.read,
          write: p.write,
          execute: p.execute,
          delete: p.delete,
          admin: p.admin,
          delegate: p.delegate,
          revoke: true
        };
}

var PermissionBuilder = {
  empty: noPermission,
  withRead: withRead,
  withWrite: withWrite,
  withExecute: withExecute,
  withDelete: withDelete,
  withAdmin: withAdmin,
  withDelegate: withDelegate,
  withRevoke: withRevoke
};

var fullPermission = {
  read: true,
  write: true,
  execute: true,
  delete: true,
  admin: true,
  delegate: true,
  revoke: true
};

var defaultFactoryConfig = {
  defaultExpirySeconds: 3600.0,
  defaultMaxDelegation: 3
};

export {
  noPermission ,
  readOnlyPermission ,
  readWritePermission ,
  fullPermission ,
  permissionIncludes ,
  permissionCombine ,
  permissionIntersect ,
  permissionToByte ,
  permissionFromByte ,
  hasAnyPermission ,
  hasNoPermission ,
  makeResourceId ,
  makeWildcardResource ,
  resourceMatches ,
  resourceEquals ,
  isExpired ,
  isValid ,
  hasPermission ,
  canDelegate ,
  remainingTime ,
  generateRandomId ,
  generateSignature ,
  defaultFactoryConfig ,
  createCapability ,
  delegateCapability ,
  validateCapability ,
  checkAccess ,
  formatCapabilityId ,
  serializeCapability ,
  deserializeCapability ,
  PermissionBuilder ,
}
/* No side effect */
