// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function parseCategory(s) {
  var match = s.toLowerCase();
  switch (match) {
    case "application" :
        return "ApplicationMedia";
    case "audio" :
        return "AudioMedia";
    case "font" :
        return "FontMedia";
    case "image" :
        return "ImageMedia";
    case "message" :
        return "MessageMedia";
    case "model" :
        return "ModelMedia";
    case "multipart" :
        return "MultipartMedia";
    case "text" :
        return "TextMedia";
    case "video" :
        return "VideoMedia";
    default:
      return "CustomMedia";
  }
}

function isUnicode(c) {
  if (typeof c === "object") {
    return false;
  }
  switch (c) {
    case "UTF8" :
    case "UTF16LE" :
    case "UTF16BE" :
        return true;
    default:
      return false;
  }
}

function charsetToString(c) {
  if (typeof c === "object") {
    return c._0.toLowerCase();
  }
  switch (c) {
    case "UTF8" :
        return "utf-8";
    case "UTF16LE" :
        return "utf-16le";
    case "UTF16BE" :
        return "utf-16be";
    case "ISO8859_1" :
        return "iso-8859-1";
    case "ASCII" :
        return "us-ascii";
    case "Windows1252" :
        return "windows-1252";
    
  }
}

function parseCharset(s) {
  var other = s.trim().toLowerCase();
  switch (other) {
    case "iso-8859-1" :
    case "latin1" :
        return "ISO8859_1";
    case "ascii" :
    case "us-ascii" :
        return "ASCII";
    case "utf-16be" :
        return "UTF16BE";
    case "utf-16le" :
        return "UTF16LE";
    case "utf-8" :
    case "utf8" :
        return "UTF8";
    case "cp1252" :
    case "windows-1252" :
        return "Windows1252";
    default:
      return {
              TAG: "OtherCharset",
              _0: other
            };
  }
}

function isValidTokenChar(c) {
  var code = c.charCodeAt(0);
  if (code >= 33.0 && code <= 126.0) {
    return !"()<>@,;:\\\"/[]?=".includes(c);
  } else {
    return false;
  }
}

var sniffableToDangerous = [
  "text/plain",
  "application/octet-stream",
  "application/x-unknown",
  "unknown/unknown"
];

function canSniffToDangerous(s) {
  return sniffableToDangerous.includes(s.toLowerCase());
}

function extractSuffix(subtype) {
  var idx = subtype.indexOf("+");
  if (idx !== -1) {
    return [
            subtype.slice(0, idx),
            subtype.slice(idx + 1 | 0)
          ];
  } else {
    return [
            subtype,
            undefined
          ];
  }
}

function parse(raw) {
  var trimmed = raw.trim();
  if (trimmed.length === 0 || trimmed.length > 1024) {
    return ;
  }
  var parts = trimmed.split(";");
  var mediaStr = parts.shift();
  if (mediaStr === undefined) {
    return ;
  }
  var idx = mediaStr.indexOf("/");
  if (idx === -1) {
    return ;
  }
  var t = mediaStr.slice(0, idx).trim().toLowerCase();
  var s = mediaStr.slice(idx + 1 | 0).trim().toLowerCase();
  if (t.length === 0 || s.length === 0) {
    return ;
  }
  var match = extractSuffix(s);
  var category = parseCategory(t);
  var media_subtype = match[0];
  var media_suffix = match[1];
  var media = {
    mediaType: t,
    subtype: media_subtype,
    suffix: media_suffix,
    category: category
  };
  var charset = {
    contents: undefined
  };
  var boundary = {
    contents: undefined
  };
  var otherParams = [];
  parts.forEach(function (param) {
        var p = param.trim();
        var eqIdx = p.indexOf("=");
        if (eqIdx === -1) {
          return ;
        }
        var name = p.slice(0, eqIdx).trim().toLowerCase();
        var value = p.slice(eqIdx + 1 | 0).trim();
        var unquoted = value.startsWith("\"") && value.endsWith("\"") ? value.slice(1, value.length - 1 | 0) : value;
        switch (name) {
          case "boundary" :
              boundary.contents = unquoted;
              return ;
          case "charset" :
              charset.contents = parseCharset(unquoted);
              return ;
          default:
            otherParams.push([
                  name,
                  unquoted
                ]);
            return ;
        }
      });
  return {
          media: media,
          charset: charset.contents,
          boundary: boundary.contents,
          params: otherParams
        };
}

function make(t, s) {
  var lower_t = t.trim().toLowerCase();
  var lower_s = s.trim().toLowerCase();
  if (lower_t.length === 0 || lower_s.length === 0) {
    return ;
  }
  if (lower_t.length > 127 || lower_s.length > 127) {
    return ;
  }
  var match = extractSuffix(lower_s);
  var category = parseCategory(lower_t);
  return {
          media: {
            mediaType: lower_t,
            subtype: match[0],
            suffix: match[1],
            category: category
          },
          charset: undefined,
          boundary: undefined,
          params: []
        };
}

function render(ct) {
  var s = ct.media.suffix;
  var base = ct.media.mediaType + "/" + ct.media.subtype + (
    s !== undefined ? "+" + s : ""
  );
  var c = ct.charset;
  var withCharset = c !== undefined ? base + "; charset=" + charsetToString(c) : base;
  var b = ct.boundary;
  var withBoundary = b !== undefined ? withCharset + "; boundary=" + b : withCharset;
  return ct.params.reduce((function (acc, param) {
                return acc + "; " + param[0] + "=" + param[1];
              }), withBoundary);
}

function withCharset(c, ct) {
  return {
          media: ct.media,
          charset: c,
          boundary: ct.boundary,
          params: ct.params
        };
}

function withBoundary(b, ct) {
  return {
          media: ct.media,
          charset: ct.charset,
          boundary: b,
          params: ct.params
        };
}

function isText(ct) {
  return ct.media.category === "TextMedia";
}

function isJson(ct) {
  if (ct.media.subtype === "json") {
    return true;
  } else {
    return Caml_obj.equal(ct.media.suffix, "json");
  }
}

function isXml(ct) {
  if (ct.media.subtype === "xml") {
    return true;
  } else {
    return Caml_obj.equal(ct.media.suffix, "xml");
  }
}

function isHtml(ct) {
  if (ct.media.mediaType === "text") {
    return ct.media.subtype === "html";
  } else {
    return false;
  }
}

function isMultipart(ct) {
  return ct.media.category === "MultipartMedia";
}

function safeFromSniffing(ct) {
  return !sniffableToDangerous.includes((ct.media.mediaType + "/" + ct.media.subtype).toLowerCase());
}

var textPlain_media = {
  mediaType: "text",
  subtype: "plain",
  suffix: undefined,
  category: "TextMedia"
};

var textPlain_charset = "UTF8";

var textPlain_params = [];

var textPlain = {
  media: textPlain_media,
  charset: textPlain_charset,
  boundary: undefined,
  params: textPlain_params
};

var textHtml_media = {
  mediaType: "text",
  subtype: "html",
  suffix: undefined,
  category: "TextMedia"
};

var textHtml_charset = "UTF8";

var textHtml_params = [];

var textHtml = {
  media: textHtml_media,
  charset: textHtml_charset,
  boundary: undefined,
  params: textHtml_params
};

var applicationJson_media = {
  mediaType: "application",
  subtype: "json",
  suffix: undefined,
  category: "ApplicationMedia"
};

var applicationJson_charset = "UTF8";

var applicationJson_params = [];

var applicationJson = {
  media: applicationJson_media,
  charset: applicationJson_charset,
  boundary: undefined,
  params: applicationJson_params
};

var applicationXml_media = {
  mediaType: "application",
  subtype: "xml",
  suffix: undefined,
  category: "ApplicationMedia"
};

var applicationXml_charset = "UTF8";

var applicationXml_params = [];

var applicationXml = {
  media: applicationXml_media,
  charset: applicationXml_charset,
  boundary: undefined,
  params: applicationXml_params
};

var applicationOctetStream_media = {
  mediaType: "application",
  subtype: "octet-stream",
  suffix: undefined,
  category: "ApplicationMedia"
};

var applicationOctetStream_params = [];

var applicationOctetStream = {
  media: applicationOctetStream_media,
  charset: undefined,
  boundary: undefined,
  params: applicationOctetStream_params
};

var formUrlencoded_media = {
  mediaType: "application",
  subtype: "x-www-form-urlencoded",
  suffix: undefined,
  category: "ApplicationMedia"
};

var formUrlencoded_params = [];

var formUrlencoded = {
  media: formUrlencoded_media,
  charset: undefined,
  boundary: undefined,
  params: formUrlencoded_params
};

export {
  parseCategory ,
  isUnicode ,
  charsetToString ,
  parseCharset ,
  isValidTokenChar ,
  sniffableToDangerous ,
  canSniffToDangerous ,
  extractSuffix ,
  parse ,
  make ,
  render ,
  withCharset ,
  withBoundary ,
  isText ,
  isJson ,
  isXml ,
  isHtml ,
  isMultipart ,
  safeFromSniffing ,
  textPlain ,
  textHtml ,
  applicationJson ,
  applicationXml ,
  applicationOctetStream ,
  formUrlencoded ,
}
/* No side effect */
