// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "rescript/lib/es6/belt_Int.js";

function parse(urlString) {
  try {
    var jsUrl = new URL(urlString);
    var portStr = jsUrl.port;
    var p = jsUrl.pathname;
    var q = jsUrl.search;
    var f = jsUrl.hash;
    return {
            scheme: jsUrl.protocol.replace(":", ""),
            host: jsUrl.hostname,
            port: portStr === "" ? undefined : Belt_Int.fromString(portStr),
            path: p === "" ? "/" : p,
            query: q === "" || q === "?" ? undefined : q.slice(1),
            fragment: f === "" || f === "#" ? undefined : f.slice(1)
          };
  }
  catch (exn){
    return ;
  }
}

function isValid(url) {
  return parse(url) !== undefined;
}

function normalize(url) {
  var parsed = parse(url);
  if (parsed === undefined) {
    return ;
  }
  var p = parsed.port;
  var portPart = p !== undefined ? ":" + String(p) : "";
  var q = parsed.query;
  var queryPart = q !== undefined ? "?" + q : "";
  var f = parsed.fragment;
  var fragmentPart = f !== undefined ? "#" + f : "";
  return parsed.scheme + "://" + parsed.host + portPart + parsed.path + queryPart + fragmentPart;
}

function getHost(url) {
  var parsed = parse(url);
  if (parsed !== undefined) {
    return parsed.host;
  }
  
}

function getPath(url) {
  var parsed = parse(url);
  if (parsed !== undefined) {
    return parsed.path;
  }
  
}

function isHttps(url) {
  var parsed = parse(url);
  if (parsed !== undefined) {
    return parsed.scheme === "https";
  } else {
    return false;
  }
}

function isHttp(url) {
  var parsed = parse(url);
  if (parsed !== undefined) {
    if (parsed.scheme === "http") {
      return true;
    } else {
      return parsed.scheme === "https";
    }
  } else {
    return false;
  }
}

export {
  parse ,
  isValid ,
  normalize ,
  getHost ,
  getPath ,
  isHttps ,
  isHttp ,
}
/* No side effect */
