// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Safe_rate_limiterJs from "../../javascript/src/safe_rate_limiter.js";

function createTokenBucket(prim0, prim1) {
  return new Safe_rate_limiterJs.TokenBucket(prim0, prim1);
}

function createSlidingWindow(prim0, prim1) {
  return new Safe_rate_limiterJs.SlidingWindowLimiter(prim0, prim1);
}

function createFixedWindow(prim0, prim1) {
  return new Safe_rate_limiterJs.FixedWindowLimiter(prim0, prim1);
}

function createLeakyBucket(prim0, prim1) {
  return new Safe_rate_limiterJs.LeakyBucket(prim0, prim1);
}

function createConcurrencyLimiter(prim) {
  return new Safe_rate_limiterJs.ConcurrencyLimiter(prim);
}

var SafeRateLimiterJs = {
  createTokenBucket: createTokenBucket,
  createSlidingWindow: createSlidingWindow,
  createFixedWindow: createFixedWindow,
  createLeakyBucket: createLeakyBucket,
  createConcurrencyLimiter: createConcurrencyLimiter
};

export {
  SafeRateLimiterJs ,
  createTokenBucket ,
  createSlidingWindow ,
  createFixedWindow ,
  createLeakyBucket ,
  createConcurrencyLimiter ,
}
/* ../../javascript/src/safe_rate_limiter.js Not a pure module */
