// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Safe_probabilityJs from "../../javascript/src/safe_probability.js";

function create(prim) {
  return Safe_probabilityJs.SafeProbability.create(prim);
}

function and_(prim0, prim1) {
  return Safe_probabilityJs.SafeProbability.and(prim0, prim1);
}

function orExclusive(prim0, prim1) {
  return Safe_probabilityJs.SafeProbability.orExclusive(prim0, prim1);
}

function not(prim) {
  return Safe_probabilityJs.SafeProbability.not(prim);
}

var SafeProbabilityJs = {
  create: create,
  and_: and_,
  orExclusive: orExclusive,
  not: not
};

export {
  SafeProbabilityJs ,
  create ,
  and_ ,
  orExclusive ,
  not ,
}
/* ../../javascript/src/safe_probability.js Not a pure module */
