// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function hasTraversal(path) {
  if (path.includes("..")) {
    return true;
  } else if (path.length > 0) {
    return path.charAt(0) === "~";
  } else {
    return false;
  }
}

function isSafePath(path) {
  var len = path.length;
  if (len === 0 || len > 4096 || hasTraversal(path)) {
    return false;
  } else {
    return !path.includes("\x00");
  }
}

function validatePath(path) {
  var len = path.length;
  if (len === 0) {
    return {
            TAG: "Error",
            _0: "InvalidPath"
          };
  } else if (len > 4096) {
    return {
            TAG: "Error",
            _0: "PathTooLong"
          };
  } else if (hasTraversal(path)) {
    return {
            TAG: "Error",
            _0: "TraversalDetected"
          };
  } else if (path.includes("\x00")) {
    return {
            TAG: "Error",
            _0: "InvalidPath"
          };
  } else {
    return {
            TAG: "Ok",
            _0: path
          };
  }
}

function sanitizeFilename(filename) {
  return filename.replace(/\\.\\./g, "_").replace(/[\\/\\\\]/g, "_").replace(/[\\x00-\\x1f]/g, "").replace(/[<>:\"\\|\\?\\*]/g, "_");
}

function safePath(base, filename) {
  if (hasTraversal(filename)) {
    return {
            TAG: "Error",
            _0: "TraversalDetected"
          };
  }
  var sanitized = sanitizeFilename(filename);
  var joined = Path.join(base, sanitized);
  var len = joined.length;
  if (len > 4096) {
    return {
            TAG: "Error",
            _0: "PathTooLong"
          };
  } else {
    return {
            TAG: "Ok",
            _0: joined
          };
  }
}

function safeJoin(base, parts) {
  var hasUnsafe = Belt_Array.some(parts, (function (part) {
          return hasTraversal(part);
        }));
  if (hasUnsafe) {
    return {
            TAG: "Error",
            _0: "TraversalDetected"
          };
  }
  var result = {
    contents: base
  };
  Belt_Array.forEach(parts, (function (part) {
          var sanitized = sanitizeFilename(part);
          result.contents = Path.join(result.contents, sanitized);
        }));
  var len = result.contents.length;
  if (len > 4096) {
    return {
            TAG: "Error",
            _0: "PathTooLong"
          };
  } else {
    return {
            TAG: "Ok",
            _0: result.contents
          };
  }
}

function readFileBounded(path, maxSize) {
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  try {
    var stat = Fs.statSync(path);
    if (stat.size > maxSize) {
      return {
              TAG: "Error",
              _0: "FileTooLarge"
            };
    }
    if (!stat.isFile()) {
      return {
              TAG: "Error",
              _0: "NotAFile"
            };
    }
    var contents = Fs.readFileSync(path, "utf8");
    return {
            TAG: "Ok",
            _0: contents
          };
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "ReadError"
            };
    }
    var message = Belt_Option.getWithDefault(e$1._1.message, "");
    if (message.includes("ENOENT")) {
      return {
              TAG: "Error",
              _0: "NotFound"
            };
    } else if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else if (message.includes("EISDIR")) {
      return {
              TAG: "Error",
              _0: "IsDirectory"
            };
    } else {
      return {
              TAG: "Error",
              _0: "ReadError"
            };
    }
  }
}

function readFile(path) {
  return readFileBounded(path, 16777216);
}

function readLines(path, maxSize) {
  var e = readFileBounded(path, maxSize);
  if (e.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: e._0.split("\n")
          };
  } else {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
}

function readLinesDefault(path) {
  return readLines(path, 16777216);
}

function writeFile(path, data) {
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  try {
    Fs.writeFileSync(path, data, "utf8");
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e$1._1.message, "");
    if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else if (message.includes("EISDIR")) {
      return {
              TAG: "Error",
              _0: "IsDirectory"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function appendFile(path, data) {
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  try {
    Fs.appendFileSync(path, data, "utf8");
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e$1._1.message, "");
    if (message.includes("ENOENT")) {
      return {
              TAG: "Error",
              _0: "NotFound"
            };
    } else if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else if (message.includes("EISDIR")) {
      return {
              TAG: "Error",
              _0: "IsDirectory"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function writeLines(path, lines) {
  var content = lines.join("\n");
  return writeFile(path, content);
}

function fileExists(path) {
  var match = validatePath(path);
  if (match.TAG !== "Ok") {
    return false;
  }
  try {
    var stat = Fs.statSync(path);
    return stat.isFile();
  }
  catch (exn){
    return false;
  }
}

function directoryExists(path) {
  var match = validatePath(path);
  if (match.TAG !== "Ok") {
    return false;
  }
  try {
    var stat = Fs.statSync(path);
    return stat.isDirectory();
  }
  catch (exn){
    return false;
  }
}

function pathExists(path) {
  var match = validatePath(path);
  if (match.TAG === "Ok") {
    return Fs.existsSync(path);
  } else {
    return false;
  }
}

function getFileSize(path) {
  var match = validatePath(path);
  if (match.TAG !== "Ok") {
    return ;
  }
  try {
    var stat = Fs.statSync(path);
    if (stat.isFile()) {
      return stat.size | 0;
    } else {
      return ;
    }
  }
  catch (exn){
    return ;
  }
}

function copyFile(srcPath, destPath) {
  var match = validatePath(srcPath);
  var match$1 = validatePath(destPath);
  if (match.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: match._0
          };
  }
  if (match$1.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: match$1._0
          };
  }
  try {
    Fs.copyFileSync(srcPath, destPath);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e._1.message, "");
    if (message.includes("ENOENT")) {
      return {
              TAG: "Error",
              _0: "NotFound"
            };
    } else if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else if (message.includes("EISDIR")) {
      return {
              TAG: "Error",
              _0: "IsDirectory"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function deleteFile(path) {
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  try {
    Fs.unlinkSync(path);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e$1._1.message, "");
    if (message.includes("ENOENT")) {
      return {
              TAG: "Ok",
              _0: undefined
            };
    } else if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else if (message.includes("EISDIR")) {
      return {
              TAG: "Error",
              _0: "IsDirectory"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function renameFile(oldPath, newPath) {
  var match = validatePath(oldPath);
  var match$1 = validatePath(newPath);
  if (match.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: match._0
          };
  }
  if (match$1.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: match$1._0
          };
  }
  try {
    Fs.renameSync(oldPath, newPath);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e._1.message, "");
    if (message.includes("ENOENT")) {
      return {
              TAG: "Error",
              _0: "NotFound"
            };
    } else if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else if (message.includes("EISDIR")) {
      return {
              TAG: "Error",
              _0: "IsDirectory"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function createDirectory(path) {
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  try {
    Fs.mkdirSync(path, {
          recursive: true
        });
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e$1._1.message, "");
    if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function removeDirectory(path, recursiveOpt) {
  var recursive = recursiveOpt !== undefined ? recursiveOpt : false;
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  try {
    Fs.rmSync(path, {
          recursive: recursive,
          force: recursive
        });
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  catch (raw_e){
    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e$1.RE_EXN_ID !== Js_exn.$$Error) {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
    var message = Belt_Option.getWithDefault(e$1._1.message, "");
    if (message.includes("ENOENT")) {
      return {
              TAG: "Ok",
              _0: undefined
            };
    } else if (message.includes("EACCES") || message.includes("EPERM")) {
      return {
              TAG: "Error",
              _0: "PermissionDenied"
            };
    } else {
      return {
              TAG: "Error",
              _0: "WriteError"
            };
    }
  }
}

function basename(path) {
  var match = validatePath(path);
  if (match.TAG === "Ok") {
    return Path.basename(path);
  }
  
}

function dirname(path) {
  var match = validatePath(path);
  if (match.TAG === "Ok") {
    return Path.dirname(path);
  }
  
}

function extname(path) {
  var match = validatePath(path);
  if (match.TAG === "Ok") {
    return Path.extname(path);
  }
  
}

function normalize(path) {
  var e = validatePath(path);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  var normalized = Path.normalize(path);
  if (hasTraversal(normalized)) {
    return {
            TAG: "Error",
            _0: "TraversalDetected"
          };
  } else {
    return {
            TAG: "Ok",
            _0: normalized
          };
  }
}

function isAbsolute(path) {
  var match = validatePath(path);
  if (match.TAG === "Ok") {
    return Path.isAbsolute(path);
  } else {
    return false;
  }
}

function writeFileAtomic(path, data) {
  var tempPath = path + ".tmp." + String(Date.now());
  var e = writeFile(tempPath, data);
  if (e.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: e._0
          };
  }
  var e$1 = renameFile(tempPath, path);
  if (e$1.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
  deleteFile(tempPath);
  return {
          TAG: "Error",
          _0: e$1._0
        };
}

function readFileOrEmpty(path) {
  var contents = readFileBounded(path, 16777216);
  if (contents.TAG === "Ok") {
    return contents._0;
  } else {
    return "";
  }
}

function readFileOrDefault(path, $$default) {
  var contents = readFileBounded(path, 16777216);
  if (contents.TAG === "Ok") {
    return contents._0;
  } else {
    return $$default;
  }
}

function ensureFile(path, defaultContent) {
  if (fileExists(path)) {
    return {
            TAG: "Ok",
            _0: undefined
          };
  } else {
    return writeFile(path, defaultContent);
  }
}

function ensureDirectory(path) {
  if (directoryExists(path)) {
    return {
            TAG: "Ok",
            _0: undefined
          };
  } else {
    return createDirectory(path);
  }
}

var maxPathLength = 4096;

var defaultMaxFileSize = 16777216;

var moveFile = renameFile;

export {
  maxPathLength ,
  defaultMaxFileSize ,
  hasTraversal ,
  isSafePath ,
  validatePath ,
  sanitizeFilename ,
  safePath ,
  safeJoin ,
  readFileBounded ,
  readFile ,
  readLines ,
  readLinesDefault ,
  writeFile ,
  appendFile ,
  writeLines ,
  fileExists ,
  directoryExists ,
  pathExists ,
  getFileSize ,
  copyFile ,
  deleteFile ,
  renameFile ,
  moveFile ,
  createDirectory ,
  removeDirectory ,
  basename ,
  dirname ,
  extname ,
  normalize ,
  isAbsolute ,
  writeFileAtomic ,
  readFileOrEmpty ,
  readFileOrDefault ,
  ensureFile ,
  ensureDirectory ,
}
/* fs Not a pure module */
