// Generated by ReScript, PLEASE EDIT WITH CARE


var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function isValid(email) {
  return emailRegex.test(email);
}

function split(email) {
  if (!emailRegex.test(email)) {
    return ;
  }
  var atPos = email.lastIndexOf("@");
  if (atPos === -1) {
    return ;
  }
  var localPart = email.slice(0, atPos);
  var domain = email.slice(atPos + 1 | 0);
  return [
          localPart,
          domain
        ];
}

function getDomain(email) {
  var match = split(email);
  if (match !== undefined) {
    return match[1];
  }
  
}

function getLocalPart(email) {
  var match = split(email);
  if (match !== undefined) {
    return match[0];
  }
  
}

function normalize(email) {
  var match = split(email);
  if (match !== undefined) {
    return match[0] + "@" + match[1].toLowerCase();
  }
  
}

export {
  emailRegex ,
  isValid ,
  split ,
  getDomain ,
  getLocalPart ,
  normalize ,
}
/* No side effect */
