// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function make(year, month, day, hourOpt, minuteOpt, secondOpt, millisecondOpt, param) {
  var hour = hourOpt !== undefined ? hourOpt : 0;
  var minute = minuteOpt !== undefined ? minuteOpt : 0;
  var second = secondOpt !== undefined ? secondOpt : 0;
  var millisecond = millisecondOpt !== undefined ? millisecondOpt : 0;
  if (month < 1 || month > 12) {
    return ;
  }
  if (day < 1 || day > 31) {
    return ;
  }
  if (hour < 0 || hour > 23) {
    return ;
  }
  if (minute < 0 || minute > 59) {
    return ;
  }
  if (second < 0 || second > 59) {
    return ;
  }
  if (millisecond < 0 || millisecond > 999) {
    return ;
  }
  var daysInMonth;
  switch (month) {
    case 2 :
        var isLeap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
        daysInMonth = isLeap ? 29 : 28;
        break;
    case 4 :
    case 6 :
    case 9 :
    case 11 :
        daysInMonth = 30;
        break;
    case 1 :
    case 3 :
    case 5 :
    case 7 :
    case 8 :
    case 10 :
    case 12 :
        daysInMonth = 31;
        break;
    default:
      daysInMonth = 0;
  }
  if (day > daysInMonth) {
    return ;
  } else {
    return {
            year: year,
            month: month,
            day: day,
            hour: hour,
            minute: minute,
            second: second,
            millisecond: millisecond
          };
  }
}

function parseIso(isoString) {
  try {
    var date = new Date(isoString);
    if (Number.isNaN(date.getTime())) {
      return ;
    } else {
      return make(date.getFullYear() | 0, (date.getMonth() | 0) + 1 | 0, date.getDate() | 0, date.getHours() | 0, date.getMinutes() | 0, date.getSeconds() | 0, date.getMilliseconds() | 0, undefined);
    }
  }
  catch (exn){
    return ;
  }
}

function now() {
  var date = new Date();
  return {
          year: date.getFullYear() | 0,
          month: (date.getMonth() | 0) + 1 | 0,
          day: date.getDate() | 0,
          hour: date.getHours() | 0,
          minute: date.getMinutes() | 0,
          second: date.getSeconds() | 0,
          millisecond: date.getMilliseconds() | 0
        };
}

function toIso(dt) {
  var pad2 = function (n) {
    if (n < 10) {
      return "0" + String(n);
    } else {
      return String(n);
    }
  };
  var pad3 = function (n) {
    if (n < 10) {
      return "00" + String(n);
    } else if (n < 100) {
      return "0" + String(n);
    } else {
      return String(n);
    }
  };
  return String(dt.year) + "-" + pad2(dt.month) + "-" + pad2(dt.day) + "T" + pad2(dt.hour) + ":" + pad2(dt.minute) + ":" + pad2(dt.second) + "." + pad3(dt.millisecond) + "Z";
}

function toTimestamp(dt) {
  return new Date(dt.year, dt.month - 1 | 0, dt.day, dt.hour, dt.minute, dt.second).getTime();
}

function fromTimestamp(timestamp) {
  if (Number.isNaN(timestamp) || !Number.isFinite(timestamp)) {
    return ;
  }
  var date = new Date(timestamp);
  return make(date.getFullYear() | 0, (date.getMonth() | 0) + 1 | 0, date.getDate() | 0, date.getHours() | 0, date.getMinutes() | 0, date.getSeconds() | 0, date.getMilliseconds() | 0, undefined);
}

function addDays(dt, days) {
  var timestamp = toTimestamp(dt) + days * 86400000.0;
  return Belt_Option.getWithDefault(fromTimestamp(timestamp), dt);
}

function addHours(dt, hours) {
  var timestamp = toTimestamp(dt) + hours * 3600000.0;
  return Belt_Option.getWithDefault(fromTimestamp(timestamp), dt);
}

function addMinutes(dt, minutes) {
  var timestamp = toTimestamp(dt) + minutes * 60000.0;
  return Belt_Option.getWithDefault(fromTimestamp(timestamp), dt);
}

function addSeconds(dt, seconds) {
  var timestamp = toTimestamp(dt) + seconds * 1000.0;
  return Belt_Option.getWithDefault(fromTimestamp(timestamp), dt);
}

function compare(a, b) {
  var tsA = toTimestamp(a);
  var tsB = toTimestamp(b);
  if (tsA < tsB) {
    return -1;
  } else if (tsA > tsB) {
    return 1;
  } else {
    return 0;
  }
}

function isBefore(a, b) {
  return compare(a, b) < 0;
}

function isAfter(a, b) {
  return compare(a, b) > 0;
}

function isEqual(a, b) {
  return compare(a, b) === 0;
}

function diffMilliseconds(a, b) {
  return toTimestamp(a) - toTimestamp(b);
}

function diffSeconds(a, b) {
  return diffMilliseconds(a, b) / 1000.0;
}

function diffMinutes(a, b) {
  return diffMilliseconds(a, b) / 60000.0;
}

function diffHours(a, b) {
  return diffMilliseconds(a, b) / 3600000.0;
}

function diffDays(a, b) {
  return diffMilliseconds(a, b) / 86400000.0;
}

function isLeapYear(year) {
  if (year % 4 === 0) {
    if (year % 100 !== 0) {
      return true;
    } else {
      return year % 400 === 0;
    }
  } else {
    return false;
  }
}

function dayOfWeek(dt) {
  var jsDate = new Date(dt.year, dt.month - 1 | 0, dt.day);
  return jsDate.getDay() | 0;
}

function dayOfYear(dt) {
  var daysInMonths = [
    31,
    28,
    31,
    30,
    31,
    30,
    31,
    31,
    30,
    31,
    30,
    31
  ];
  var feb = isLeapYear(dt.year) ? 29 : 28;
  var days = dt.day;
  for(var i = 0 ,i_finish = dt.month - 2 | 0; i <= i_finish; ++i){
    var monthDays = i === 1 ? feb : daysInMonths[i];
    days = days + monthDays | 0;
  }
  return days;
}

export {
  make ,
  parseIso ,
  now ,
  toIso ,
  toTimestamp ,
  fromTimestamp ,
  addDays ,
  addHours ,
  addMinutes ,
  addSeconds ,
  compare ,
  isBefore ,
  isAfter ,
  isEqual ,
  diffMilliseconds ,
  diffSeconds ,
  diffMinutes ,
  diffHours ,
  diffDays ,
  isLeapYear ,
  dayOfWeek ,
  dayOfYear ,
}
/* No side effect */
