// Generated by ReScript, PLEASE EDIT WITH CARE


function $$isFinite(n) {
  return Number.isFinite(n);
}

function $$isNaN(n) {
  return Number.isNaN(n);
}

function div(numerator, denominator) {
  if (denominator === 0.0) {
    return ;
  }
  var result = numerator / denominator;
  if (Number.isFinite(result)) {
    return result;
  }
  
}

function divOr($$default, numerator, denominator) {
  var v = div(numerator, denominator);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

function sqrt(n) {
  if (n < 0.0) {
    return ;
  } else {
    return Math.sqrt(n);
  }
}

function log(n) {
  if (n <= 0.0) {
    return ;
  } else {
    return Math.log(n);
  }
}

function log10(n) {
  if (n <= 0.0) {
    return ;
  } else {
    return Math.log10(n);
  }
}

function log2(n) {
  if (n <= 0.0) {
    return ;
  } else {
    return Math.log2(n);
  }
}

function pow(base, exp) {
  var result = Math.pow(base, exp);
  if (Number.isFinite(result)) {
    return result;
  }
  
}

function clamp(lo, hi, value) {
  if (value < lo) {
    return lo;
  } else if (value > hi) {
    return hi;
  } else {
    return value;
  }
}

function roundTo(decimals, value) {
  var factor = Math.pow(10.0, decimals);
  return Math.round(value * factor) / factor;
}

function floorTo(decimals, value) {
  var factor = Math.pow(10.0, decimals);
  return Math.floor(value * factor) / factor;
}

function ceilTo(decimals, value) {
  var factor = Math.pow(10.0, decimals);
  return Math.ceil(value * factor) / factor;
}

function fromString(str) {
  var trimmed = str.trim();
  if (trimmed.length === 0) {
    return ;
  }
  var parsed = Number(trimmed);
  if (Number.isNaN(parsed)) {
    return ;
  } else {
    return parsed;
  }
}

function toFixed(decimals, value) {
  return value.toFixed(decimals);
}

function toPrecision(digits, value) {
  return value.toPrecision(digits);
}

function approxEqual(epsilon, a, b) {
  return Math.abs(a - b) <= epsilon;
}

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function inverseLerp(a, b, value) {
  if (a === b) {
    return ;
  } else {
    return (value - a) / (b - a);
  }
}

function remap(inMin, inMax, outMin, outMax, value) {
  var t = inverseLerp(inMin, inMax, value);
  if (t !== undefined) {
    return lerp(outMin, outMax, t);
  }
  
}

function inRange(value, lo, hi) {
  if (value >= lo) {
    return value <= hi;
  } else {
    return false;
  }
}

function sign(n) {
  if (n < 0.0) {
    return -1;
  } else if (n > 0.0) {
    return 1;
  } else {
    return 0;
  }
}

function safeMod(a, b) {
  if (b === 0.0) {
    return ;
  }
  var result = a % b;
  if (result < 0.0 && b > 0.0 || result > 0.0 && b < 0.0) {
    return result + b;
  } else {
    return result;
  }
}

export {
  $$isFinite ,
  $$isNaN ,
  div ,
  divOr ,
  sqrt ,
  log ,
  log10 ,
  log2 ,
  pow ,
  clamp ,
  roundTo ,
  floorTo ,
  ceilTo ,
  fromString ,
  toFixed ,
  toPrecision ,
  approxEqual ,
  lerp ,
  inverseLerp ,
  remap ,
  inRange ,
  sign ,
  safeMod ,
}
/* No side effect */
