// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Safe_graphJs from "../../javascript/src/safe_graph.js";

function forStrings(prim) {
  return Safe_graphJs.DirectedGraph.forStrings();
}

function forNumbers(prim) {
  return Safe_graphJs.DirectedGraph.forNumbers();
}

function undirectedForStrings(prim) {
  return Safe_graphJs.UndirectedGraph.forStrings();
}

var SafeGraphJs = {
  forStrings: forStrings,
  forNumbers: forNumbers,
  undirectedForStrings: undirectedForStrings
};

var directedForStrings = forStrings;

var directedForNumbers = forNumbers;

export {
  SafeGraphJs ,
  directedForStrings ,
  directedForNumbers ,
  undirectedForStrings ,
}
/* ../../javascript/src/safe_graph.js Not a pure module */
