// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function getDialingCode(country) {
  if (typeof country === "object") {
    return "";
  }
  switch (country) {
    case "US" :
    case "CA" :
        return "1";
    case "GB" :
        return "44";
    case "DE" :
        return "49";
    case "FR" :
        return "33";
    case "IT" :
        return "39";
    case "ES" :
        return "34";
    case "NL" :
        return "31";
    case "BE" :
        return "32";
    case "CH" :
        return "41";
    case "AT" :
        return "43";
    case "AU" :
        return "61";
    case "NZ" :
        return "64";
    case "JP" :
        return "81";
    case "KR" :
        return "82";
    case "CN" :
        return "86";
    case "HK" :
        return "852";
    case "SG" :
        return "65";
    case "IN" :
        return "91";
    case "PK" :
        return "92";
    case "BD" :
        return "880";
    case "ID" :
        return "62";
    case "MY" :
        return "60";
    case "TH" :
        return "66";
    case "VN" :
        return "84";
    case "PH" :
        return "63";
    case "TW" :
        return "886";
    case "BR" :
        return "55";
    case "MX" :
        return "52";
    case "AR" :
        return "54";
    case "CO" :
        return "57";
    case "CL" :
        return "56";
    case "PE" :
        return "51";
    case "ZA" :
        return "27";
    case "NG" :
        return "234";
    case "EG" :
        return "20";
    case "KE" :
        return "254";
    case "GH" :
        return "233";
    case "MA" :
        return "212";
    case "AE" :
        return "971";
    case "SA" :
        return "966";
    case "IL" :
        return "972";
    case "TR" :
        return "90";
    case "RU" :
        return "7";
    case "UA" :
        return "380";
    case "PL" :
        return "48";
    case "CZ" :
        return "420";
    case "SE" :
        return "46";
    case "NO" :
        return "47";
    case "DK" :
        return "45";
    case "FI" :
        return "358";
    case "IE" :
        return "353";
    case "PT" :
        return "351";
    case "GR" :
        return "30";
    
  }
}

function parseCountryCode(code) {
  var upper = code.trim().toUpperCase();
  switch (upper) {
    case "AE" :
        return {
                TAG: "Ok",
                _0: "AE"
              };
    case "AR" :
        return {
                TAG: "Ok",
                _0: "AR"
              };
    case "AT" :
        return {
                TAG: "Ok",
                _0: "AT"
              };
    case "AU" :
        return {
                TAG: "Ok",
                _0: "AU"
              };
    case "BD" :
        return {
                TAG: "Ok",
                _0: "BD"
              };
    case "BE" :
        return {
                TAG: "Ok",
                _0: "BE"
              };
    case "BR" :
        return {
                TAG: "Ok",
                _0: "BR"
              };
    case "CA" :
        return {
                TAG: "Ok",
                _0: "CA"
              };
    case "CH" :
        return {
                TAG: "Ok",
                _0: "CH"
              };
    case "CL" :
        return {
                TAG: "Ok",
                _0: "CL"
              };
    case "CN" :
        return {
                TAG: "Ok",
                _0: "CN"
              };
    case "CO" :
        return {
                TAG: "Ok",
                _0: "CO"
              };
    case "CZ" :
        return {
                TAG: "Ok",
                _0: "CZ"
              };
    case "DE" :
        return {
                TAG: "Ok",
                _0: "DE"
              };
    case "DK" :
        return {
                TAG: "Ok",
                _0: "DK"
              };
    case "EG" :
        return {
                TAG: "Ok",
                _0: "EG"
              };
    case "ES" :
        return {
                TAG: "Ok",
                _0: "ES"
              };
    case "FI" :
        return {
                TAG: "Ok",
                _0: "FI"
              };
    case "FR" :
        return {
                TAG: "Ok",
                _0: "FR"
              };
    case "GH" :
        return {
                TAG: "Ok",
                _0: "GH"
              };
    case "GR" :
        return {
                TAG: "Ok",
                _0: "GR"
              };
    case "HK" :
        return {
                TAG: "Ok",
                _0: "HK"
              };
    case "ID" :
        return {
                TAG: "Ok",
                _0: "ID"
              };
    case "IE" :
        return {
                TAG: "Ok",
                _0: "IE"
              };
    case "IL" :
        return {
                TAG: "Ok",
                _0: "IL"
              };
    case "IN" :
        return {
                TAG: "Ok",
                _0: "IN"
              };
    case "IT" :
        return {
                TAG: "Ok",
                _0: "IT"
              };
    case "JP" :
        return {
                TAG: "Ok",
                _0: "JP"
              };
    case "KE" :
        return {
                TAG: "Ok",
                _0: "KE"
              };
    case "KR" :
        return {
                TAG: "Ok",
                _0: "KR"
              };
    case "MA" :
        return {
                TAG: "Ok",
                _0: "MA"
              };
    case "MX" :
        return {
                TAG: "Ok",
                _0: "MX"
              };
    case "MY" :
        return {
                TAG: "Ok",
                _0: "MY"
              };
    case "NG" :
        return {
                TAG: "Ok",
                _0: "NG"
              };
    case "NL" :
        return {
                TAG: "Ok",
                _0: "NL"
              };
    case "NO" :
        return {
                TAG: "Ok",
                _0: "NO"
              };
    case "NZ" :
        return {
                TAG: "Ok",
                _0: "NZ"
              };
    case "PE" :
        return {
                TAG: "Ok",
                _0: "PE"
              };
    case "PH" :
        return {
                TAG: "Ok",
                _0: "PH"
              };
    case "PK" :
        return {
                TAG: "Ok",
                _0: "PK"
              };
    case "PL" :
        return {
                TAG: "Ok",
                _0: "PL"
              };
    case "PT" :
        return {
                TAG: "Ok",
                _0: "PT"
              };
    case "RU" :
        return {
                TAG: "Ok",
                _0: "RU"
              };
    case "SA" :
        return {
                TAG: "Ok",
                _0: "SA"
              };
    case "SE" :
        return {
                TAG: "Ok",
                _0: "SE"
              };
    case "SG" :
        return {
                TAG: "Ok",
                _0: "SG"
              };
    case "TH" :
        return {
                TAG: "Ok",
                _0: "TH"
              };
    case "TR" :
        return {
                TAG: "Ok",
                _0: "TR"
              };
    case "TW" :
        return {
                TAG: "Ok",
                _0: "TW"
              };
    case "UA" :
        return {
                TAG: "Ok",
                _0: "UA"
              };
    case "GB" :
    case "UK" :
        return {
                TAG: "Ok",
                _0: "GB"
              };
    case "US" :
        return {
                TAG: "Ok",
                _0: "US"
              };
    case "VN" :
        return {
                TAG: "Ok",
                _0: "VN"
              };
    case "ZA" :
        return {
                TAG: "Ok",
                _0: "ZA"
              };
    default:
      if (upper.length === 2) {
        return {
                TAG: "Ok",
                _0: {
                  TAG: "Other",
                  _0: upper
                }
              };
      } else {
        return {
                TAG: "Error",
                _0: "InvalidCountryCode"
              };
      }
  }
}

function countryCodeToString(country) {
  if (typeof country === "object") {
    return country._0;
  }
  switch (country) {
    case "US" :
        return "US";
    case "CA" :
        return "CA";
    case "GB" :
        return "GB";
    case "DE" :
        return "DE";
    case "FR" :
        return "FR";
    case "IT" :
        return "IT";
    case "ES" :
        return "ES";
    case "NL" :
        return "NL";
    case "BE" :
        return "BE";
    case "CH" :
        return "CH";
    case "AT" :
        return "AT";
    case "AU" :
        return "AU";
    case "NZ" :
        return "NZ";
    case "JP" :
        return "JP";
    case "KR" :
        return "KR";
    case "CN" :
        return "CN";
    case "HK" :
        return "HK";
    case "SG" :
        return "SG";
    case "IN" :
        return "IN";
    case "PK" :
        return "PK";
    case "BD" :
        return "BD";
    case "ID" :
        return "ID";
    case "MY" :
        return "MY";
    case "TH" :
        return "TH";
    case "VN" :
        return "VN";
    case "PH" :
        return "PH";
    case "TW" :
        return "TW";
    case "BR" :
        return "BR";
    case "MX" :
        return "MX";
    case "AR" :
        return "AR";
    case "CO" :
        return "CO";
    case "CL" :
        return "CL";
    case "PE" :
        return "PE";
    case "ZA" :
        return "ZA";
    case "NG" :
        return "NG";
    case "EG" :
        return "EG";
    case "KE" :
        return "KE";
    case "GH" :
        return "GH";
    case "MA" :
        return "MA";
    case "AE" :
        return "AE";
    case "SA" :
        return "SA";
    case "IL" :
        return "IL";
    case "TR" :
        return "TR";
    case "RU" :
        return "RU";
    case "UA" :
        return "UA";
    case "PL" :
        return "PL";
    case "CZ" :
        return "CZ";
    case "SE" :
        return "SE";
    case "NO" :
        return "NO";
    case "DK" :
        return "DK";
    case "FI" :
        return "FI";
    case "IE" :
        return "IE";
    case "PT" :
        return "PT";
    case "GR" :
        return "GR";
    
  }
}

function extractDigits(input) {
  return input.replace(/[^0-9]/g, "");
}

function hasValidCharacters(input) {
  return /^[0-9+\\-\\.\\(\\)\\s#*ext]+$/i.test(input);
}

function extractExtension(input) {
  var extPatterns = [
    /[,;]\\s*ext\\.?\\s*(\\d+)$/i,
    /\\s+ext\\.?\\s*(\\d+)$/i,
    /\\s+x\\.?(\\d+)$/i,
    /\\s+#(\\d+)$/
  ];
  var foundExtension = {
    contents: undefined
  };
  var remainingInput = {
    contents: input
  };
  Belt_Array.forEach(extPatterns, (function (pattern) {
          if (!Belt_Option.isNone(foundExtension.contents)) {
            return ;
          }
          var result = pattern.exec(input);
          if (result === null) {
            return ;
          }
          var extMatch = Belt_Array.get(result, 1);
          if (extMatch === undefined) {
            return ;
          }
          var extMatch$1 = Caml_option.valFromOption(extMatch);
          if (!(extMatch$1 == null)) {
            foundExtension.contents = extMatch$1;
            remainingInput.contents = input.slice(0, input.length - Belt_Option.getWithDefault(Caml_option.nullable_to_opt(Caml_array.get(result, 0)), "").length | 0);
            return ;
          }
          
        }));
  return [
          remainingInput.contents,
          foundExtension.contents
        ];
}

function parseWithCountry(phoneStr, country) {
  var trimmed = phoneStr.trim();
  if (!hasValidCharacters(trimmed)) {
    return {
            TAG: "Error",
            _0: "InvalidCharacters"
          };
  }
  var match = extractExtension(trimmed);
  var digits = extractDigits(match[0]);
  var dialingCode = getDialingCode(country);
  var length = digits.length;
  if (length < 6) {
    return {
            TAG: "Error",
            _0: "TooShort"
          };
  }
  if (length > 15) {
    return {
            TAG: "Error",
            _0: "TooLong"
          };
  }
  var nationalNumber = digits.startsWith(dialingCode) ? digits.slice(dialingCode.length) : (
      digits.startsWith("00" + dialingCode) ? digits.slice(2 + dialingCode.length | 0) : digits
    );
  return {
          TAG: "Ok",
          _0: {
            countryCode: country,
            dialingCode: dialingCode,
            nationalNumber: nationalNumber,
            extension: match[1],
            rawInput: phoneStr
          }
        };
}

function parse(phoneStr) {
  var trimmed = phoneStr.trim();
  if (!hasValidCharacters(trimmed)) {
    return {
            TAG: "Error",
            _0: "InvalidCharacters"
          };
  }
  var match = extractExtension(trimmed);
  var digits = extractDigits(match[0]);
  var length = digits.length;
  if (length < 6) {
    return {
            TAG: "Error",
            _0: "TooShort"
          };
  }
  if (length > 15) {
    return {
            TAG: "Error",
            _0: "TooLong"
          };
  }
  var startsWithPlus = trimmed.startsWith("+");
  var startsWithZeros = digits.startsWith("00");
  var match$1;
  if (startsWithPlus || startsWithZeros) {
    var codeStart = startsWithZeros ? digits.slice(2) : digits;
    var threeDigitCodes = [
      [
        "880",
        "BD"
      ],
      [
        "886",
        "TW"
      ],
      [
        "852",
        "HK"
      ],
      [
        "971",
        "AE"
      ],
      [
        "966",
        "SA"
      ],
      [
        "972",
        "IL"
      ],
      [
        "380",
        "UA"
      ],
      [
        "420",
        "CZ"
      ],
      [
        "358",
        "FI"
      ],
      [
        "353",
        "IE"
      ],
      [
        "351",
        "PT"
      ],
      [
        "234",
        "NG"
      ],
      [
        "254",
        "KE"
      ],
      [
        "233",
        "GH"
      ],
      [
        "212",
        "MA"
      ]
    ];
    var found3 = Belt_Array.reduce(threeDigitCodes, undefined, (function (acc, param) {
            if (acc !== undefined) {
              return acc;
            } else if (codeStart.startsWith(param[0])) {
              return [
                      param[1],
                      codeStart.slice(3)
                    ];
            } else {
              return ;
            }
          }));
    if (found3 !== undefined) {
      match$1 = found3;
    } else {
      var twoDigitCodes = [
        [
          "44",
          "GB"
        ],
        [
          "49",
          "DE"
        ],
        [
          "33",
          "FR"
        ],
        [
          "39",
          "IT"
        ],
        [
          "34",
          "ES"
        ],
        [
          "31",
          "NL"
        ],
        [
          "32",
          "BE"
        ],
        [
          "41",
          "CH"
        ],
        [
          "43",
          "AT"
        ],
        [
          "61",
          "AU"
        ],
        [
          "64",
          "NZ"
        ],
        [
          "81",
          "JP"
        ],
        [
          "82",
          "KR"
        ],
        [
          "86",
          "CN"
        ],
        [
          "65",
          "SG"
        ],
        [
          "91",
          "IN"
        ],
        [
          "92",
          "PK"
        ],
        [
          "62",
          "ID"
        ],
        [
          "60",
          "MY"
        ],
        [
          "66",
          "TH"
        ],
        [
          "84",
          "VN"
        ],
        [
          "63",
          "PH"
        ],
        [
          "55",
          "BR"
        ],
        [
          "52",
          "MX"
        ],
        [
          "54",
          "AR"
        ],
        [
          "57",
          "CO"
        ],
        [
          "56",
          "CL"
        ],
        [
          "51",
          "PE"
        ],
        [
          "27",
          "ZA"
        ],
        [
          "20",
          "EG"
        ],
        [
          "90",
          "TR"
        ],
        [
          "48",
          "PL"
        ],
        [
          "46",
          "SE"
        ],
        [
          "47",
          "NO"
        ],
        [
          "45",
          "DK"
        ],
        [
          "30",
          "GR"
        ]
      ];
      var found2 = Belt_Array.reduce(twoDigitCodes, undefined, (function (acc, param) {
              if (acc !== undefined) {
                return acc;
              } else if (codeStart.startsWith(param[0])) {
                return [
                        param[1],
                        codeStart.slice(2)
                      ];
              } else {
                return ;
              }
            }));
      match$1 = found2 !== undefined ? found2 : (
          codeStart.startsWith("1") ? [
              "US",
              codeStart.slice(1)
            ] : (
              codeStart.startsWith("7") ? [
                  "RU",
                  codeStart.slice(1)
                ] : [
                  "US",
                  codeStart
                ]
            )
        );
    }
  } else {
    match$1 = [
      "US",
      digits
    ];
  }
  var detectedCountry = match$1[0];
  return {
          TAG: "Ok",
          _0: {
            countryCode: detectedCountry,
            dialingCode: getDialingCode(detectedCountry),
            nationalNumber: match$1[1],
            extension: match[1],
            rawInput: phoneStr
          }
        };
}

function isValid(phoneStr) {
  var match = parse(phoneStr);
  if (match.TAG === "Ok") {
    return true;
  } else {
    return false;
  }
}

function formatE164(phone) {
  var base = "+" + phone.dialingCode + phone.nationalNumber;
  var ext = phone.extension;
  if (ext !== undefined) {
    return base + ";ext=" + ext;
  } else {
    return base;
  }
}

function formatNational(phone) {
  var digits = phone.nationalNumber;
  var match = phone.countryCode;
  var formatted;
  var exit = 0;
  if (typeof match !== "object") {
    switch (match) {
      case "US" :
      case "CA" :
          exit = 1;
          break;
      case "GB" :
          formatted = digits.length >= 10 ? digits.slice(0, 5) + " " + digits.slice(5) : digits;
          break;
      case "DE" :
      case "FR" :
      case "IT" :
      case "ES" :
          exit = 2;
          break;
      default:
        formatted = digits;
    }
  } else {
    formatted = digits;
  }
  switch (exit) {
    case 1 :
        formatted = digits.length === 10 ? "(" + digits.slice(0, 3) + ") " + digits.slice(3, 6) + "-" + digits.slice(6) : digits;
        break;
    case 2 :
        formatted = digits.length >= 10 ? digits.slice(0, 3) + " " + digits.slice(3, 7) + " " + digits.slice(7) : digits;
        break;
    
  }
  var ext = phone.extension;
  if (ext !== undefined) {
    return formatted + " ext. " + ext;
  } else {
    return formatted;
  }
}

function formatInternational(phone) {
  var base = "+" + phone.dialingCode + " " + phone.nationalNumber;
  var ext = phone.extension;
  if (ext !== undefined) {
    return base + " ext. " + ext;
  } else {
    return base;
  }
}

function getCountryCode(phone) {
  return phone.countryCode;
}

function getNationalNumber(phone) {
  return phone.nationalNumber;
}

function getExtension(phone) {
  return phone.extension;
}

function equal(phoneA, phoneB) {
  if (Caml_obj.equal(phoneA.countryCode, phoneB.countryCode) && phoneA.nationalNumber === phoneB.nationalNumber) {
    return Caml_obj.equal(phoneA.extension, phoneB.extension);
  } else {
    return false;
  }
}

export {
  getDialingCode ,
  parseCountryCode ,
  countryCodeToString ,
  extractDigits ,
  hasValidCharacters ,
  extractExtension ,
  parseWithCountry ,
  parse ,
  isValid ,
  formatE164 ,
  formatNational ,
  formatInternational ,
  getCountryCode ,
  getNationalNumber ,
  getExtension ,
  equal ,
}
/* No side effect */
