// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Safe_monotonicJs from "../../javascript/src/safe_monotonic.js";

function createCounter(prim0, prim1) {
  return new Safe_monotonicJs.MonotonicCounter(prim0, prim1);
}

function createTimestamp(prim) {
  return new Safe_monotonicJs.MonotonicTimestamp();
}

function createId(prim) {
  return new Safe_monotonicJs.MonotonicID(prim);
}

function createSequence(prim0, prim1, prim2) {
  return new Safe_monotonicJs.MonotonicSequence(prim0, prim1, prim2);
}

function createVersion(prim0, prim1, prim2) {
  return new Safe_monotonicJs.MonotonicVersion(prim0, prim1, prim2);
}

var SafeMonotonicJs = {
  createCounter: createCounter,
  createTimestamp: createTimestamp,
  createId: createId,
  createSequence: createSequence,
  createVersion: createVersion
};

export {
  SafeMonotonicJs ,
  createCounter ,
  createTimestamp ,
  createId ,
  createSequence ,
  createVersion ,
}
/* ../../javascript/src/safe_monotonic.js Not a pure module */
