// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FfiJs from "../../javascript/src/ffi.js";
import * as ResultJs from "../../javascript/src/result.js";

function getLib(prim) {
  return FfiJs.getLib();
}

function isAvailable(prim) {
  return FfiJs.isAvailable();
}

function getLoadError(prim) {
  return FfiJs.getLoadError();
}

function closeFfi(prim) {
  FfiJs.close();
}

function encodeString(prim) {
  return FfiJs.encodeString(prim);
}

function jsOk(prim) {
  return ResultJs.ok(prim);
}

function jsErr(prim) {
  return ResultJs.err(prim);
}

function jsIsOk(prim) {
  return ResultJs.isOk(prim);
}

function jsIsErr(prim) {
  return ResultJs.isErr(prim);
}

function init() {
  return FfiJs.isAvailable();
}

function isInitialized() {
  return FfiJs.isAvailable();
}

function deinit() {
  FfiJs.close();
}

export {
  getLib ,
  isAvailable ,
  getLoadError ,
  closeFfi ,
  encodeString ,
  jsOk ,
  jsErr ,
  jsIsOk ,
  jsIsErr ,
  init ,
  isInitialized ,
  deinit ,
}
/* ../../javascript/src/ffi.js Not a pure module */
