// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Proven_Bitwise from "./Proven_Bitwise.res.js";

var defaultConfig = {
  openDelim: "{{",
  closeDelim: "}}",
  escapeContext: "EscapeHtml",
  maxDepth: 10,
  stripWhitespace: false
};

function valueToString(value) {
  if (typeof value !== "object") {
    return "";
  }
  switch (value.TAG) {
    case "VString" :
        return value._0;
    case "VInteger" :
    case "VFloat" :
        return String(value._0);
    case "VBoolean" :
        if (value._0) {
          return "true";
        } else {
          return "false";
        }
    case "VArray" :
        return "[Array]";
    
  }
}

function valueIsTruthy(value) {
  if (typeof value !== "object") {
    return false;
  }
  switch (value.TAG) {
    case "VString" :
        return value._0.length > 0;
    case "VInteger" :
        return value._0 !== 0;
    case "VFloat" :
        return value._0 !== 0.0;
    case "VBoolean" :
        return value._0;
    case "VArray" :
        return value._0.length !== 0;
    
  }
}

function escapeHtml(value) {
  var length = value.length;
  var result = "";
  for(var i = 0; i < length; ++i){
    var $$char = value.charAt(i);
    switch ($$char) {
      case "&" :
          result = result + "&amp;";
          break;
      case "'" :
          result = result + "&#x27;";
          break;
      case "/" :
          result = result + "&#x2F;";
          break;
      case "<" :
          result = result + "&lt;";
          break;
      case ">" :
          result = result + "&gt;";
          break;
      case "\"" :
          result = result + "&quot;";
          break;
      default:
        result = result + $$char;
    }
  }
  return result;
}

function escapeHtmlAttribute(value) {
  var length = value.length;
  var result = "";
  for(var i = 0; i < length; ++i){
    var $$char = value.charAt(i);
    switch ($$char) {
      case "&" :
          result = result + "&amp;";
          break;
      case "'" :
          result = result + "&#x27;";
          break;
      case "<" :
          result = result + "&lt;";
          break;
      case "=" :
          result = result + "&#x3D;";
          break;
      case ">" :
          result = result + "&gt;";
          break;
      case "\"" :
          result = result + "&quot;";
          break;
      case "`" :
          result = result + "&#x60;";
          break;
      default:
        result = result + $$char;
    }
  }
  return result;
}

function escapeUrl(value) {
  var hexChars = "0123456789ABCDEF";
  var length = value.length;
  var result = "";
  for(var i = 0; i < length; ++i){
    var $$char = value.charAt(i);
    if ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.~".includes($$char)) {
      result = result + $$char;
    } else {
      var code = $$char.charCodeAt(0) | 0;
      var high = Proven_Bitwise.lsr(code, 4);
      var low = Proven_Bitwise.land(code, 15);
      result = result + "%" + hexChars.charAt(high) + hexChars.charAt(low);
    }
  }
  return result;
}

function escapeJavaScript(value) {
  var length = value.length;
  var result = "";
  var hexChars = "0123456789ABCDEF";
  for(var i = 0; i < length; ++i){
    var $$char = value.charAt(i);
    switch ($$char) {
      case "'" :
          result = result + "\\'";
          break;
      case "/" :
          result = result + "\\/";
          break;
      case "<" :
          result = result + "\\u003C";
          break;
      case ">" :
          result = result + "\\u003E";
          break;
      case "\"" :
          result = result + "\\\"";
          break;
      case "\\" :
          result = result + "\\\\";
          break;
      case "\n" :
          result = result + "\\n";
          break;
      case "\r" :
          result = result + "\\r";
          break;
      case "\t" :
          result = result + "\\t";
          break;
      default:
        var code = $$char.charCodeAt(0) | 0;
        if (code < 32) {
          var h1 = Proven_Bitwise.lsr(code, 12);
          var h2 = Proven_Bitwise.land(Proven_Bitwise.lsr(code, 8), 15);
          var h3 = Proven_Bitwise.land(Proven_Bitwise.lsr(code, 4), 15);
          var h4 = Proven_Bitwise.land(code, 15);
          result = result + "\\u" + hexChars.charAt(h1) + hexChars.charAt(h2) + hexChars.charAt(h3) + hexChars.charAt(h4);
        } else {
          result = result + $$char;
        }
    }
  }
  return result;
}

function escapeCss(value) {
  var length = value.length;
  var result = "";
  var hexChars = "0123456789ABCDEF";
  for(var i = 0; i < length; ++i){
    var $$char = value.charAt(i);
    var code = $$char.charCodeAt(0) | 0;
    var isAlnum = code >= 48 && code <= 57 || code >= 65 && code <= 90 || code >= 97 && code <= 122;
    if (isAlnum) {
      result = result + $$char;
    } else {
      var h1 = Proven_Bitwise.lsr(code, 4);
      var h2 = Proven_Bitwise.land(code, 15);
      result = result + "\\" + hexChars.charAt(h1) + hexChars.charAt(h2) + " ";
    }
  }
  return result;
}

function escapeSql(value) {
  var length = value.length;
  var result = "";
  for(var i = 0; i < length; ++i){
    var $$char = value.charAt(i);
    result = $$char === "'" ? result + "''" : result + $$char;
  }
  return result;
}

function escapeForContext(value, context) {
  switch (context) {
    case "EscapeNone" :
        return value;
    case "EscapeHtml" :
        return escapeHtml(value);
    case "EscapeHtmlAttribute" :
        return escapeHtmlAttribute(value);
    case "EscapeUrl" :
        return escapeUrl(value);
    case "EscapeJavaScript" :
        return escapeJavaScript(value);
    case "EscapeCss" :
        return escapeCss(value);
    case "EscapeSql" :
        return escapeSql(value);
    
  }
}

function renderWithLookup(template, lookup, config) {
  var result = "";
  var pos = 0;
  var templateLen = template.length;
  var error;
  while(pos < templateLen && Belt_Option.isNone(error)) {
    var start = template.indexOf(config.openDelim, pos);
    if (start !== -1) {
      result = result + template.slice(pos, start);
      var varStart = start + config.openDelim.length | 0;
      var endPos = template.indexOf(config.closeDelim, varStart);
      if (endPos !== -1) {
        var varContent = template.slice(varStart, endPos);
        if (varContent.includes(config.openDelim)) {
          error = "NestedDelimiters";
        } else {
          var varName = config.stripWhitespace ? varContent.trim() : varContent;
          var match = varName.startsWith("!") ? [
              "EscapeNone",
              varName.slice(1)
            ] : (
              varName.startsWith("html:") ? [
                  "EscapeHtml",
                  varName.slice(5)
                ] : (
                  varName.startsWith("url:") ? [
                      "EscapeUrl",
                      varName.slice(4)
                    ] : (
                      varName.startsWith("js:") ? [
                          "EscapeJavaScript",
                          varName.slice(3)
                        ] : (
                          varName.startsWith("css:") ? [
                              "EscapeCss",
                              varName.slice(4)
                            ] : (
                              varName.startsWith("sql:") ? [
                                  "EscapeSql",
                                  varName.slice(4)
                                ] : [
                                  config.escapeContext,
                                  varName
                                ]
                            )
                        )
                    )
                )
            );
          var trimmedName = match[1].trim();
          var value = lookup(trimmedName);
          if (value !== undefined) {
            var strValue = valueToString(value);
            var escaped = escapeForContext(strValue, match[0]);
            result = result + escaped;
          } else {
            error = "UnknownVariable";
          }
          pos = endPos + config.closeDelim.length | 0;
        }
      } else {
        error = "UnclosedDelimiter";
      }
    } else {
      result = result + template.slice(pos);
      pos = templateLen;
    }
  };
  var e = error;
  if (e !== undefined) {
    return {
            TAG: "Error",
            _0: e
          };
  } else {
    return {
            TAG: "Ok",
            _0: result
          };
  }
}

function render(template, variables, config) {
  var lookup = function (name) {
    return Js_dict.get(variables, name);
  };
  return renderWithLookup(template, lookup, config);
}

function renderSimple(template, variables) {
  return render(template, variables, defaultConfig);
}

function isValid(template, config) {
  var depth = 0;
  var pos = 0;
  var templateLen = template.length;
  var valid = true;
  while(pos < templateLen && valid) {
    var openPos = template.indexOf(config.openDelim, pos);
    if (openPos !== -1) {
      depth = depth + 1 | 0;
      pos = openPos + config.openDelim.length | 0;
      var closePos = template.indexOf(config.closeDelim, pos);
      if (closePos !== -1) {
        depth = depth - 1 | 0;
        pos = closePos + config.closeDelim.length | 0;
      } else {
        valid = false;
      }
    } else {
      pos = templateLen;
    }
  };
  if (valid) {
    return depth === 0;
  } else {
    return false;
  }
}

function extractVariables(template, config) {
  var variables = [];
  var pos = 0;
  var templateLen = template.length;
  while(pos < templateLen) {
    var start = template.indexOf(config.openDelim, pos);
    if (start !== -1) {
      var varStart = start + config.openDelim.length | 0;
      var endPos = template.indexOf(config.closeDelim, varStart);
      if (endPos !== -1) {
        var varContent = template.slice(varStart, endPos);
        var varName = varContent.trim();
        var actualName;
        if (varName.startsWith("!")) {
          actualName = varName.slice(1);
        } else {
          var colonPos = varName.indexOf(":");
          actualName = colonPos !== -1 ? varName.slice(colonPos + 1 | 0) : varName;
        }
        var trimmedName = actualName.trim();
        var exists = Belt_Array.some(variables, (function(trimmedName){
            return function (v) {
              return v === trimmedName;
            }
            }(trimmedName)));
        if (!exists) {
          variables = Belt_Array.concat(variables, [trimmedName]);
        }
        pos = endPos + config.closeDelim.length | 0;
      } else {
        pos = templateLen;
      }
    } else {
      pos = templateLen;
    }
  };
  return variables;
}

function escapeContextToString(ctx) {
  switch (ctx) {
    case "EscapeNone" :
        return "none";
    case "EscapeHtml" :
        return "html";
    case "EscapeHtmlAttribute" :
        return "html_attribute";
    case "EscapeUrl" :
        return "url";
    case "EscapeJavaScript" :
        return "javascript";
    case "EscapeCss" :
        return "css";
    case "EscapeSql" :
        return "sql";
    
  }
}

function defaultEscapeContext() {
  return "EscapeHtml";
}

function templateErrorToString(error) {
  switch (error) {
    case "InvalidTemplate" :
        return "Invalid template";
    case "UnknownVariable" :
        return "Unknown variable";
    case "UnclosedDelimiter" :
        return "Unclosed delimiter";
    case "NestedDelimiters" :
        return "Nested delimiters are not allowed";
    case "InvalidEscapeSequence" :
        return "Invalid escape sequence";
    case "MaxDepthExceeded" :
        return "Maximum nesting depth exceeded";
    case "CircularReference" :
        return "Circular reference detected";
    
  }
}

function fromString(s) {
  return {
          TAG: "VString",
          _0: s
        };
}

function fromInt(i) {
  return {
          TAG: "VInteger",
          _0: i
        };
}

function fromFloat(f) {
  return {
          TAG: "VFloat",
          _0: f
        };
}

function fromBool(b) {
  return {
          TAG: "VBoolean",
          _0: b
        };
}

function $$null() {
  return "VNull";
}

function fromArray(a) {
  return {
          TAG: "VArray",
          _0: a
        };
}

export {
  defaultConfig ,
  valueToString ,
  valueIsTruthy ,
  escapeHtml ,
  escapeHtmlAttribute ,
  escapeUrl ,
  escapeJavaScript ,
  escapeCss ,
  escapeSql ,
  escapeForContext ,
  renderWithLookup ,
  render ,
  renderSimple ,
  isValid ,
  extractVariables ,
  escapeContextToString ,
  defaultEscapeContext ,
  templateErrorToString ,
  fromString ,
  fromInt ,
  fromFloat ,
  fromBool ,
  $$null ,
  fromArray ,
}
/* No side effect */
