// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

var table = Belt_Array.make(256, 0);

for(var i = 0; i <= 255; ++i){
  var c = i;
  for(var _for = 0; _for <= 7; ++_for){
    c = (c & 1) === 1 ? (c >>> 1) ^ -306674912 : (c >>> 1);
  }
  table[i] = c;
}

function crc32Bytes(data) {
  var crc = {
    contents: -1
  };
  Belt_Array.forEach(data, (function ($$byte) {
          var index = (crc.contents ^ $$byte) & 255;
          var tableValue = table[index];
          crc.contents = (crc.contents >>> 8) ^ tableValue;
        }));
  return crc.contents ^ -1;
}

function crc32(data) {
  var bytes = Belt_Array.makeBy(data.length, (function (i) {
          return data.charCodeAt(i) | 0;
        }));
  return crc32Bytes(bytes);
}

function adler32Bytes(data) {
  var a = {
    contents: 1
  };
  var b = {
    contents: 0
  };
  Belt_Array.forEach(data, (function ($$byte) {
          a.contents = (a.contents + $$byte | 0) % 65521;
          b.contents = (b.contents + a.contents | 0) % 65521;
        }));
  return (b.contents << 16) | a.contents;
}

function adler32(data) {
  var bytes = Belt_Array.makeBy(data.length, (function (i) {
          return data.charCodeAt(i) | 0;
        }));
  return adler32Bytes(bytes);
}

function luhnCheck(digits) {
  var length = digits.length;
  if (length === 0) {
    return false;
  }
  var sum = 0;
  var alternate = false;
  var valid = true;
  var i = length - 1 | 0;
  while(valid && i >= 0) {
    var c = digits.charAt(i);
    var code = c.charCodeAt(0) | 0;
    if (code < 48 || code > 57) {
      valid = false;
    } else {
      var digit = code - 48 | 0;
      if (alternate) {
        digit = (digit << 1);
        if (digit > 9) {
          digit = digit - 9 | 0;
        }
        
      }
      sum = sum + digit | 0;
      alternate = !alternate;
    }
    i = i - 1 | 0;
  };
  if (valid) {
    return sum % 10 === 0;
  } else {
    return false;
  }
}

function luhnCheckDigit(partialNumber) {
  var length = partialNumber.length;
  if (length === 0) {
    return ;
  }
  var sum = 0;
  var alternate = true;
  var valid = true;
  var i = length - 1 | 0;
  while(valid && i >= 0) {
    var c = partialNumber.charAt(i);
    var code = c.charCodeAt(0) | 0;
    if (code < 48 || code > 57) {
      valid = false;
    } else {
      var digit = code - 48 | 0;
      if (alternate) {
        digit = (digit << 1);
        if (digit > 9) {
          digit = digit - 9 | 0;
        }
        
      }
      sum = sum + digit | 0;
      alternate = !alternate;
    }
    i = i - 1 | 0;
  };
  if (valid) {
    return (10 - sum % 10 | 0) % 10;
  }
  
}

function isValidISBN10(isbn) {
  var clean = Belt_Array.make(10, 0);
  var idx = 0;
  for(var i = 0 ,i_finish = isbn.length; i < i_finish; ++i){
    if (idx < 10) {
      var c = isbn.charAt(i);
      var code = c.charCodeAt(0) | 0;
      if (code >= 48 && code <= 57) {
        clean[idx] = code - 48 | 0;
        idx = idx + 1 | 0;
      } else if ((c === "X" || c === "x") && idx === 9) {
        clean[idx] = 10;
        idx = idx + 1 | 0;
      }
      
    }
    
  }
  if (idx !== 10) {
    return false;
  }
  var sum = 0;
  for(var i$1 = 0; i$1 <= 9; ++i$1){
    var digit = clean[i$1];
    sum = sum + Math.imul(digit, 10 - i$1 | 0) | 0;
  }
  return sum % 11 === 0;
}

function isValidISBN13(isbn) {
  var clean = Belt_Array.make(13, 0);
  var idx = 0;
  for(var i = 0 ,i_finish = isbn.length; i < i_finish; ++i){
    if (idx < 13) {
      var c = isbn.charAt(i);
      var code = c.charCodeAt(0) | 0;
      if (code >= 48 && code <= 57) {
        clean[idx] = code - 48 | 0;
        idx = idx + 1 | 0;
      }
      
    }
    
  }
  if (idx !== 13) {
    return false;
  }
  var sum = 0;
  for(var i$1 = 0; i$1 <= 12; ++i$1){
    var digit = clean[i$1];
    var mult = i$1 % 2 === 0 ? 1 : 3;
    sum = sum + Math.imul(digit, mult) | 0;
  }
  return sum % 10 === 0;
}

function isValidISBN(isbn) {
  var digitCount = 0;
  var hasX = false;
  for(var i = 0 ,i_finish = isbn.length; i < i_finish; ++i){
    var c = isbn.charAt(i);
    var code = c.charCodeAt(0) | 0;
    if (code >= 48 && code <= 57) {
      digitCount = digitCount + 1 | 0;
    } else if (c === "X" || c === "x") {
      hasX = true;
    }
    
  }
  if (digitCount === 10 || digitCount === 9 && hasX) {
    return isValidISBN10(isbn);
  } else if (digitCount === 13) {
    return isValidISBN13(isbn);
  } else {
    return false;
  }
}

function xorChecksumBytes(data) {
  return Belt_Array.reduce(data, 0, (function (acc, $$byte) {
                return acc ^ $$byte;
              }));
}

function xorChecksum(data) {
  var result = 0;
  for(var i = 0 ,i_finish = data.length; i < i_finish; ++i){
    var code = data.charCodeAt(i) | 0;
    result = result ^ code & 255;
  }
  return result;
}

function fletcher16Bytes(data) {
  var sum1 = {
    contents: 0
  };
  var sum2 = {
    contents: 0
  };
  Belt_Array.forEach(data, (function ($$byte) {
          sum1.contents = (sum1.contents + $$byte | 0) % 255;
          sum2.contents = (sum2.contents + sum1.contents | 0) % 255;
        }));
  return (sum2.contents << 8) | sum1.contents;
}

function fletcher16(data) {
  var bytes = Belt_Array.makeBy(data.length, (function (i) {
          return data.charCodeAt(i) & 255;
        }));
  return fletcher16Bytes(bytes);
}

function fletcher32Bytes(data) {
  var sum1 = {
    contents: 0
  };
  var sum2 = {
    contents: 0
  };
  Belt_Array.forEach(data, (function ($$byte) {
          sum1.contents = (sum1.contents + $$byte | 0) % 65535;
          sum2.contents = (sum2.contents + sum1.contents | 0) % 65535;
        }));
  return (sum2.contents << 16) | sum1.contents;
}

function fletcher32(data) {
  var bytes = Belt_Array.makeBy(data.length, (function (i) {
          return data.charCodeAt(i) & 255;
        }));
  return fletcher32Bytes(bytes);
}

function sumChecksum(data) {
  var sum = 0;
  for(var i = 0 ,i_finish = data.length; i < i_finish; ++i){
    var code = data.charCodeAt(i) | 0;
    sum = sum + (code & 255) | 0;
  }
  return sum & 255;
}

function twosComplementChecksum(data) {
  var sum = sumChecksum(data);
  return PervasivesU.lnot(sum) + 1 & 255;
}

function verifyChecksum(data, checksum) {
  var sum = sumChecksum(data);
  return (sum + checksum & 255) === 0;
}

function toHex(value, widthOpt) {
  var width = widthOpt !== undefined ? widthOpt : 8;
  var result = "";
  var v = value & -1;
  for(var _for = 0; _for < width; ++_for){
    var nibble = v & 15;
    result = "0123456789ABCDEF".charAt(nibble) + result;
    v = (v >>> 4);
  }
  return result;
}

function toHexLower(value, widthOpt) {
  var width = widthOpt !== undefined ? widthOpt : 8;
  return toHex(value, width).toLowerCase();
}

function isValidIBAN(iban) {
  var clean = iban.replace(/\\s/g, "").toUpperCase();
  var length = clean.length;
  if (length < 15 || length > 34) {
    return false;
  }
  var rearranged = clean.substring(4, length) + clean.substring(0, 4);
  var numericStr = "";
  var valid = true;
  for(var i = 0 ,i_finish = rearranged.length; i < i_finish; ++i){
    if (valid) {
      var c = rearranged.charAt(i);
      var code = c.charCodeAt(0) | 0;
      if (code >= 48 && code <= 57) {
        numericStr = numericStr + c;
      } else if (code >= 65 && code <= 90) {
        var num = code - 55 | 0;
        numericStr = numericStr + String(num);
      } else {
        valid = false;
      }
    }
    
  }
  if (!valid) {
    return false;
  }
  var remainder = 0;
  for(var i$1 = 0 ,i_finish$1 = numericStr.length; i$1 < i_finish$1; ++i$1){
    var c$1 = numericStr.charAt(i$1);
    var digit = (c$1.charCodeAt(0) | 0) - 48 | 0;
    remainder = (Math.imul(remainder, 10) + digit | 0) % 97;
  }
  return remainder === 1;
}

function dammCheck(digits) {
  var table = [
    [
      0,
      3,
      1,
      7,
      5,
      9,
      8,
      6,
      4,
      2
    ],
    [
      7,
      0,
      9,
      2,
      1,
      5,
      4,
      8,
      6,
      3
    ],
    [
      4,
      2,
      0,
      6,
      8,
      7,
      1,
      3,
      5,
      9
    ],
    [
      1,
      7,
      5,
      0,
      9,
      8,
      3,
      4,
      2,
      6
    ],
    [
      6,
      1,
      2,
      3,
      0,
      4,
      5,
      9,
      7,
      8
    ],
    [
      3,
      6,
      7,
      4,
      2,
      0,
      9,
      5,
      8,
      1
    ],
    [
      5,
      8,
      6,
      9,
      7,
      2,
      0,
      1,
      3,
      4
    ],
    [
      8,
      9,
      4,
      5,
      3,
      6,
      2,
      0,
      1,
      7
    ],
    [
      9,
      4,
      3,
      8,
      6,
      1,
      7,
      2,
      0,
      5
    ],
    [
      2,
      5,
      8,
      1,
      4,
      3,
      6,
      7,
      9,
      0
    ]
  ];
  var interim = 0;
  var valid = true;
  for(var i = 0 ,i_finish = digits.length; i < i_finish; ++i){
    if (valid) {
      var c = digits.charAt(i);
      var code = c.charCodeAt(0) | 0;
      if (code < 48 || code > 57) {
        valid = false;
      } else {
        var digit = code - 48 | 0;
        var row = table[interim];
        interim = row[digit];
      }
    }
    
  }
  if (valid) {
    return interim === 0;
  } else {
    return false;
  }
}

function verhoeffCheck(digits) {
  var d = [
    [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    [
      1,
      2,
      3,
      4,
      0,
      6,
      7,
      8,
      9,
      5
    ],
    [
      2,
      3,
      4,
      0,
      1,
      7,
      8,
      9,
      5,
      6
    ],
    [
      3,
      4,
      0,
      1,
      2,
      8,
      9,
      5,
      6,
      7
    ],
    [
      4,
      0,
      1,
      2,
      3,
      9,
      5,
      6,
      7,
      8
    ],
    [
      5,
      9,
      8,
      7,
      6,
      0,
      4,
      3,
      2,
      1
    ],
    [
      6,
      5,
      9,
      8,
      7,
      1,
      0,
      4,
      3,
      2
    ],
    [
      7,
      6,
      5,
      9,
      8,
      2,
      1,
      0,
      4,
      3
    ],
    [
      8,
      7,
      6,
      5,
      9,
      3,
      2,
      1,
      0,
      4
    ],
    [
      9,
      8,
      7,
      6,
      5,
      4,
      3,
      2,
      1,
      0
    ]
  ];
  var p = [
    [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    [
      1,
      5,
      7,
      6,
      2,
      8,
      3,
      0,
      9,
      4
    ],
    [
      5,
      8,
      0,
      3,
      7,
      9,
      6,
      1,
      4,
      2
    ],
    [
      8,
      9,
      1,
      6,
      0,
      4,
      3,
      5,
      2,
      7
    ],
    [
      9,
      4,
      5,
      3,
      1,
      2,
      6,
      8,
      7,
      0
    ],
    [
      4,
      2,
      8,
      6,
      5,
      7,
      3,
      9,
      0,
      1
    ],
    [
      2,
      7,
      9,
      3,
      8,
      0,
      6,
      4,
      1,
      5
    ],
    [
      7,
      0,
      4,
      6,
      9,
      1,
      3,
      2,
      5,
      8
    ]
  ];
  var c = 0;
  var length = digits.length;
  var valid = true;
  for(var i = 0; i < length; ++i){
    if (valid) {
      var $$char = digits.charAt((length - 1 | 0) - i | 0);
      var code = $$char.charCodeAt(0) | 0;
      if (code < 48 || code > 57) {
        valid = false;
      } else {
        var ni = code - 48 | 0;
        var pRow = p[i % 8];
        var pVal = pRow[ni];
        var dRow = d[c];
        c = dRow[pVal];
      }
    }
    
  }
  if (valid) {
    return c === 0;
  } else {
    return false;
  }
}

var crc32Table = table;

export {
  crc32Table ,
  crc32Bytes ,
  crc32 ,
  adler32Bytes ,
  adler32 ,
  luhnCheck ,
  luhnCheckDigit ,
  isValidISBN10 ,
  isValidISBN13 ,
  isValidISBN ,
  xorChecksumBytes ,
  xorChecksum ,
  fletcher16Bytes ,
  fletcher16 ,
  fletcher32Bytes ,
  fletcher32 ,
  sumChecksum ,
  twosComplementChecksum ,
  verifyChecksum ,
  toHex ,
  toHexLower ,
  isValidIBAN ,
  dammCheck ,
  verhoeffCheck ,
}
/* table Not a pure module */
