// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

function getDecimalPlaces(currency) {
  if (typeof currency === "object") {
    return 2;
  }
  switch (currency) {
    case "JPY" :
    case "KRW" :
    case "VND" :
    case "CLP" :
        return 0;
    case "BTC" :
        return 8;
    case "ETH" :
        return 18;
    default:
      return 2;
  }
}

function parseCurrencyCode(code) {
  var upper = code.trim().toUpperCase();
  switch (upper) {
    case "AED" :
        return {
                TAG: "Ok",
                _0: "AED"
              };
    case "ARS" :
        return {
                TAG: "Ok",
                _0: "ARS"
              };
    case "AUD" :
        return {
                TAG: "Ok",
                _0: "AUD"
              };
    case "BRL" :
        return {
                TAG: "Ok",
                _0: "BRL"
              };
    case "BTC" :
        return {
                TAG: "Ok",
                _0: "BTC"
              };
    case "CAD" :
        return {
                TAG: "Ok",
                _0: "CAD"
              };
    case "CHF" :
        return {
                TAG: "Ok",
                _0: "CHF"
              };
    case "CLP" :
        return {
                TAG: "Ok",
                _0: "CLP"
              };
    case "CNY" :
        return {
                TAG: "Ok",
                _0: "CNY"
              };
    case "COP" :
        return {
                TAG: "Ok",
                _0: "COP"
              };
    case "CZK" :
        return {
                TAG: "Ok",
                _0: "CZK"
              };
    case "DKK" :
        return {
                TAG: "Ok",
                _0: "DKK"
              };
    case "EGP" :
        return {
                TAG: "Ok",
                _0: "EGP"
              };
    case "ETH" :
        return {
                TAG: "Ok",
                _0: "ETH"
              };
    case "EUR" :
        return {
                TAG: "Ok",
                _0: "EUR"
              };
    case "GBP" :
        return {
                TAG: "Ok",
                _0: "GBP"
              };
    case "GHS" :
        return {
                TAG: "Ok",
                _0: "GHS"
              };
    case "HKD" :
        return {
                TAG: "Ok",
                _0: "HKD"
              };
    case "HUF" :
        return {
                TAG: "Ok",
                _0: "HUF"
              };
    case "IDR" :
        return {
                TAG: "Ok",
                _0: "IDR"
              };
    case "ILS" :
        return {
                TAG: "Ok",
                _0: "ILS"
              };
    case "INR" :
        return {
                TAG: "Ok",
                _0: "INR"
              };
    case "JPY" :
        return {
                TAG: "Ok",
                _0: "JPY"
              };
    case "KES" :
        return {
                TAG: "Ok",
                _0: "KES"
              };
    case "KRW" :
        return {
                TAG: "Ok",
                _0: "KRW"
              };
    case "MXN" :
        return {
                TAG: "Ok",
                _0: "MXN"
              };
    case "MYR" :
        return {
                TAG: "Ok",
                _0: "MYR"
              };
    case "NGN" :
        return {
                TAG: "Ok",
                _0: "NGN"
              };
    case "NOK" :
        return {
                TAG: "Ok",
                _0: "NOK"
              };
    case "NZD" :
        return {
                TAG: "Ok",
                _0: "NZD"
              };
    case "PEN" :
        return {
                TAG: "Ok",
                _0: "PEN"
              };
    case "PHP" :
        return {
                TAG: "Ok",
                _0: "PHP"
              };
    case "PLN" :
        return {
                TAG: "Ok",
                _0: "PLN"
              };
    case "RUB" :
        return {
                TAG: "Ok",
                _0: "RUB"
              };
    case "SAR" :
        return {
                TAG: "Ok",
                _0: "SAR"
              };
    case "SEK" :
        return {
                TAG: "Ok",
                _0: "SEK"
              };
    case "SGD" :
        return {
                TAG: "Ok",
                _0: "SGD"
              };
    case "THB" :
        return {
                TAG: "Ok",
                _0: "THB"
              };
    case "TRY" :
        return {
                TAG: "Ok",
                _0: "TRY"
              };
    case "TWD" :
        return {
                TAG: "Ok",
                _0: "TWD"
              };
    case "UAH" :
        return {
                TAG: "Ok",
                _0: "UAH"
              };
    case "USD" :
        return {
                TAG: "Ok",
                _0: "USD"
              };
    case "VND" :
        return {
                TAG: "Ok",
                _0: "VND"
              };
    case "ZAR" :
        return {
                TAG: "Ok",
                _0: "ZAR"
              };
    default:
      if (upper.length >= 3 && upper.length <= 4) {
        return {
                TAG: "Ok",
                _0: {
                  TAG: "Other",
                  _0: upper
                }
              };
      } else {
        return {
                TAG: "Error",
                _0: "InvalidCurrencyCode"
              };
      }
  }
}

function currencyCodeToString(currency) {
  if (typeof currency === "object") {
    return currency._0;
  }
  switch (currency) {
    case "USD" :
        return "USD";
    case "EUR" :
        return "EUR";
    case "GBP" :
        return "GBP";
    case "JPY" :
        return "JPY";
    case "CHF" :
        return "CHF";
    case "CAD" :
        return "CAD";
    case "AUD" :
        return "AUD";
    case "NZD" :
        return "NZD";
    case "CNY" :
        return "CNY";
    case "HKD" :
        return "HKD";
    case "SGD" :
        return "SGD";
    case "SEK" :
        return "SEK";
    case "NOK" :
        return "NOK";
    case "DKK" :
        return "DKK";
    case "KRW" :
        return "KRW";
    case "INR" :
        return "INR";
    case "BRL" :
        return "BRL";
    case "MXN" :
        return "MXN";
    case "ZAR" :
        return "ZAR";
    case "RUB" :
        return "RUB";
    case "TRY" :
        return "TRY";
    case "PLN" :
        return "PLN";
    case "THB" :
        return "THB";
    case "IDR" :
        return "IDR";
    case "MYR" :
        return "MYR";
    case "PHP" :
        return "PHP";
    case "VND" :
        return "VND";
    case "AED" :
        return "AED";
    case "SAR" :
        return "SAR";
    case "ILS" :
        return "ILS";
    case "TWD" :
        return "TWD";
    case "CZK" :
        return "CZK";
    case "HUF" :
        return "HUF";
    case "CLP" :
        return "CLP";
    case "COP" :
        return "COP";
    case "PEN" :
        return "PEN";
    case "ARS" :
        return "ARS";
    case "EGP" :
        return "EGP";
    case "NGN" :
        return "NGN";
    case "KES" :
        return "KES";
    case "GHS" :
        return "GHS";
    case "UAH" :
        return "UAH";
    case "BTC" :
        return "BTC";
    case "ETH" :
        return "ETH";
    
  }
}

function fromMinorUnits(currency, minorUnits) {
  return {
          currency: currency,
          minorUnits: minorUnits
        };
}

function fromMajorUnits(currency, majorUnits) {
  var decimalPlaces = getDecimalPlaces(currency);
  var multiplier = Math.pow(10.0, decimalPlaces);
  var minorUnitsFloat = majorUnits * multiplier;
  var minorUnits = Math.round(minorUnitsFloat) | 0;
  if (minorUnitsFloat > PervasivesU.max_int || minorUnitsFloat < PervasivesU.min_int) {
    return {
            TAG: "Error",
            _0: "Overflow"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: currency,
              minorUnits: minorUnits
            }
          };
  }
}

function toMinorUnits(money) {
  return money.minorUnits;
}

function toMajorUnits(money) {
  var decimalPlaces = getDecimalPlaces(money.currency);
  var divisor = Math.pow(10.0, decimalPlaces);
  return money.minorUnits / divisor;
}

function add(moneyA, moneyB) {
  if (Caml_obj.notequal(moneyA.currency, moneyB.currency)) {
    return {
            TAG: "Error",
            _0: "CurrencyMismatch"
          };
  }
  var result = moneyA.minorUnits + moneyB.minorUnits | 0;
  if (moneyA.minorUnits > 0 && moneyB.minorUnits > 0 && result < 0) {
    return {
            TAG: "Error",
            _0: "Overflow"
          };
  } else if (moneyA.minorUnits < 0 && moneyB.minorUnits < 0 && result > 0) {
    return {
            TAG: "Error",
            _0: "Underflow"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: moneyA.currency,
              minorUnits: result
            }
          };
  }
}

function subtract(moneyA, moneyB) {
  if (Caml_obj.notequal(moneyA.currency, moneyB.currency)) {
    return {
            TAG: "Error",
            _0: "CurrencyMismatch"
          };
  }
  var result = moneyA.minorUnits - moneyB.minorUnits | 0;
  if (moneyA.minorUnits > 0 && moneyB.minorUnits < 0 && result < 0) {
    return {
            TAG: "Error",
            _0: "Overflow"
          };
  } else if (moneyA.minorUnits < 0 && moneyB.minorUnits > 0 && result > 0) {
    return {
            TAG: "Error",
            _0: "Underflow"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: moneyA.currency,
              minorUnits: result
            }
          };
  }
}

function multiply(money, multiplier) {
  if (multiplier === 0) {
    return {
            TAG: "Ok",
            _0: {
              currency: money.currency,
              minorUnits: 0
            }
          };
  }
  var result = Math.imul(money.minorUnits, multiplier);
  if (Caml_int32.div(result, multiplier) !== money.minorUnits) {
    if (multiplier > 0 && money.minorUnits > 0 || multiplier < 0 && money.minorUnits < 0) {
      return {
              TAG: "Error",
              _0: "Overflow"
            };
    } else {
      return {
              TAG: "Error",
              _0: "Underflow"
            };
    }
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: money.currency,
              minorUnits: result
            }
          };
  }
}

function divide(money, divisor) {
  if (divisor === 0) {
    return {
            TAG: "Error",
            _0: "DivisionByZero"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: money.currency,
              minorUnits: Caml_int32.div(money.minorUnits, divisor)
            }
          };
  }
}

function percentOf(money, percent) {
  var scaled = Math.imul(money.minorUnits, percent);
  if (percent !== 0 && Caml_int32.div(scaled, percent) !== money.minorUnits) {
    return {
            TAG: "Error",
            _0: "Overflow"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: money.currency,
              minorUnits: scaled / 100 | 0
            }
          };
  }
}

function isZero(money) {
  return money.minorUnits === 0;
}

function isPositive(money) {
  return money.minorUnits > 0;
}

function isNegative(money) {
  return money.minorUnits < 0;
}

function negate(money) {
  if (money.minorUnits === PervasivesU.min_int) {
    return {
            TAG: "Error",
            _0: "Overflow"
          };
  } else {
    return {
            TAG: "Ok",
            _0: {
              currency: money.currency,
              minorUnits: -money.minorUnits | 0
            }
          };
  }
}

function abs(money) {
  if (money.minorUnits === PervasivesU.min_int) {
    return {
            TAG: "Error",
            _0: "Overflow"
          };
  } else if (money.minorUnits < 0) {
    return {
            TAG: "Ok",
            _0: {
              currency: money.currency,
              minorUnits: -money.minorUnits | 0
            }
          };
  } else {
    return {
            TAG: "Ok",
            _0: money
          };
  }
}

function compare(moneyA, moneyB) {
  if (Caml_obj.notequal(moneyA.currency, moneyB.currency)) {
    return {
            TAG: "Error",
            _0: "CurrencyMismatch"
          };
  } else if (moneyA.minorUnits < moneyB.minorUnits) {
    return {
            TAG: "Ok",
            _0: -1
          };
  } else if (moneyA.minorUnits > moneyB.minorUnits) {
    return {
            TAG: "Ok",
            _0: 1
          };
  } else {
    return {
            TAG: "Ok",
            _0: 0
          };
  }
}

function equal(moneyA, moneyB) {
  if (Caml_obj.notequal(moneyA.currency, moneyB.currency)) {
    return {
            TAG: "Error",
            _0: "CurrencyMismatch"
          };
  } else {
    return {
            TAG: "Ok",
            _0: moneyA.minorUnits === moneyB.minorUnits
          };
  }
}

function format(money) {
  var decimalPlaces = getDecimalPlaces(money.currency);
  var majorUnits = toMajorUnits(money);
  var absValue = Math.abs(majorUnits);
  var sign = majorUnits < 0.0 ? "-" : "";
  var formatted = decimalPlaces === 0 ? String(absValue) : absValue.toFixed(decimalPlaces);
  return sign + currencyCodeToString(money.currency) + " " + formatted;
}

function formatWithSymbol(money) {
  var match = money.currency;
  var symbol;
  if (typeof match !== "object") {
    switch (match) {
      case "EUR" :
          symbol = "\u20AC";
          break;
      case "GBP" :
          symbol = "\u00A3";
          break;
      case "CHF" :
          symbol = "CHF ";
          break;
      case "JPY" :
      case "CNY" :
          symbol = "\u00A5";
          break;
      case "KRW" :
          symbol = "\u20A9";
          break;
      case "INR" :
          symbol = "\u20B9";
          break;
      case "BRL" :
          symbol = "R$";
          break;
      case "RUB" :
          symbol = "\u20BD";
          break;
      case "TRY" :
          symbol = "\u20BA";
          break;
      case "PLN" :
          symbol = "z\u0142";
          break;
      case "THB" :
          symbol = "\u0E3F";
          break;
      case "ILS" :
          symbol = "\u20AA";
          break;
      case "USD" :
      case "CAD" :
      case "AUD" :
      case "NZD" :
      case "HKD" :
      case "SGD" :
      case "MXN" :
      case "COP" :
          symbol = "$";
          break;
      case "BTC" :
          symbol = "\u20BF";
          break;
      case "ETH" :
          symbol = "\u039E";
          break;
      default:
        symbol = currencyCodeToString(money.currency) + " ";
    }
  } else {
    symbol = currencyCodeToString(money.currency) + " ";
  }
  var decimalPlaces = getDecimalPlaces(money.currency);
  var majorUnits = toMajorUnits(money);
  var absValue = Math.abs(majorUnits);
  var sign = majorUnits < 0.0 ? "-" : "";
  var formatted = decimalPlaces === 0 ? String(absValue) : absValue.toFixed(decimalPlaces);
  return sign + symbol + formatted;
}

function zero(currency) {
  return {
          currency: currency,
          minorUnits: 0
        };
}

export {
  getDecimalPlaces ,
  parseCurrencyCode ,
  currencyCodeToString ,
  fromMinorUnits ,
  fromMajorUnits ,
  toMinorUnits ,
  toMajorUnits ,
  add ,
  subtract ,
  multiply ,
  divide ,
  percentOf ,
  isZero ,
  isPositive ,
  isNegative ,
  negate ,
  abs ,
  compare ,
  equal ,
  format ,
  formatWithSymbol ,
  zero ,
}
/* No side effect */
