// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function escapeSql(value) {
  return value.replace(/'/g, "''");
}

function escapeHtml(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#x27;");
}

function escapeJs(value) {
  return value.replace(/\\\\/g, "\\\\").replace(/\"/g, "\\\"").replace(/'/g, "\\'").replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
}

function toCodePoints(str) {
  var length = str.length;
  if (length === 0) {
    return {
            TAG: "Ok",
            _0: []
          };
  }
  var codes = Belt_Array.make(length, 0);
  var valid = true;
  var errorIdx = 0;
  for(var i = 0; i < length; ++i){
    if (valid) {
      var code = str.charCodeAt(i) | 0;
      if (code > 255) {
        valid = false;
        errorIdx = i;
      } else {
        codes[i] = code;
      }
    }
    
  }
  if (valid) {
    return {
            TAG: "Ok",
            _0: codes
          };
  } else {
    return {
            TAG: "Error",
            _0: "Character at position " + String(errorIdx) + " is outside ASCII range"
          };
  }
}

function fromCodePoints(codes) {
  var length = codes.length;
  if (length === 0) {
    return {
            TAG: "Ok",
            _0: ""
          };
  }
  var valid = true;
  var errorIdx = 0;
  var result = "";
  for(var i = 0; i < length; ++i){
    if (valid) {
      var code = codes[i];
      if (code < 0 || code > 65535) {
        valid = false;
        errorIdx = i;
      } else {
        result = result + String.fromCharCode(code);
      }
    }
    
  }
  if (valid) {
    return {
            TAG: "Ok",
            _0: result
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid code point at position " + String(errorIdx)
          };
  }
}

function isAscii(str) {
  var length = str.length;
  var valid = true;
  for(var i = 0; i < length; ++i){
    if (valid) {
      var code = str.charCodeAt(i) | 0;
      if (code > 127) {
        valid = false;
      }
      
    }
    
  }
  return valid;
}

function isPrintableAscii(str) {
  var length = str.length;
  var valid = true;
  for(var i = 0; i < length; ++i){
    if (valid) {
      var code = str.charCodeAt(i) | 0;
      if (code < 32 || code > 126) {
        valid = false;
      }
      
    }
    
  }
  return valid;
}

export {
  escapeSql ,
  escapeHtml ,
  escapeJs ,
  toCodePoints ,
  fromCodePoints ,
  isAscii ,
  isPrintableAscii ,
}
/* No side effect */
